### ISSUE TITLE
updating backblaze.exe itself

### ISSUE THREAD

**Issue by thehatch2002** [JonathanTreffler/backblaze-personal-wine-container#104]
I have done this before in the past.  My docker get reinstalled and it wiped my updated blackblaze window program out.  I downloaded a newer updated version of the application and ran docker run to get it to install.  some reason I am unable to get winefile to open nor get the new file up open up on the vnc.

root@Spawn:~# docker exec --user app backblaze_personal_backup winefile
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.

and 

root@Spawn:~# docker exec --user app backblaze_personal_backup wine /config/wine/drive_c/backblazenew.exe

root@228cfab9fdba:/config/wine/drive_c# ls -la
total 57868
drwxrwxrwx 1 app app      238 Jan 28 18:31  .
drwxrwxrwx 1 app app      168 Jan 28 18:31  ..
-rw-rw-rw- 1 app app 30124640 Jan 28 18:08  backblazenew.exe
-rw-r--r-- 1 app app     4798 Jan 28 18:15  backblaze-wine-startapp.log
-rw-r--r-- 1 app app 29120304 Jan 27 02:05  install_backblaze.exe
drwxrwxrwx 1 app app       62 Jul  5  2023  ProgramData
drwxrwxrwx 1 app app      118 Jul  5  2023 'Program Files'
drwxrwxrwx 1 app app      136 Jul  5  2023 'Program Files (x86)'
drwxrwxrwx 1 app app       18 Jul  5  2023  users
drwxrwxrwx 1 app app      492 Jan 27 01:58  windows
root@228cfab9fdba:/config/wine/drive_c# 

root@228cfab9fdba:/config/wine/dosdevices# ls -la
total 16
drwxrwxrwx 1 app app  20 Jan 28 18:15 .
drwxrwxrwx 1 app app 168 Jan 28 18:31 ..
lrwxrwxrwx 1 app app  10 Jul  8  2023 c: -> ../drive_c
lrwxrwxrwx 1 app app  10 Jan 28 18:15 com1 -> /dev/ttyS0
lrwxrwxrwx 1 app app   9 Jul  8  2023 d: -> /drive_d/
lrwxrwxrwx 1 app app   1 Jul  8  2023 z: -> /
root@228cfab9fdba:/config/wine/dosdevices# 

maybe someone can help me figure out how to get winfile to open or get the blackblazenew.exe to pop up on the vnc

**Comment by traktuner** [comment]
Hello!
Thank you very much for using the project!
In version 1.6 we introduced an autoupdate feature.
By default, the app is being updated to a known-good version (which we tested). But you can override it with an environment variable to update to the latest official Backblaze version.
Please have a look at the readme:
https://github.com/JonathanTreffler/backblaze-personal-wine-container?tab=readme-ov-file#environment-variables
Hope that helps!

**Comment by traktuner** [comment]
Could you please post the docker log output or a screenshot of the error that pops up, please?

**Comment by kooori** [comment]
This is happening to me too! Screen shot below.

![image](https://github.com/JonathanTreffler/backblaze-personal-wine-container/assets/64124640/04d66633-b8dd-46ad-a040-d3307a8c0fd5)

**Comment by traktuner** [comment]
> This is happening to me too! Screen shot below.

Hey,
we have updated the troubleshooting section in the readme.
You may have to add USER_ID and GROUP_ID to your docker run command (depending on your environment and the permission schemes on your Docker host)
Also please try the :ubuntu22 tag instead (or :ubuntu20) which may fix some other issues as well
`'tessypowder/backblaze-personal-wine:ubuntu22'`

**Comment by traktuner** [comment]
Great, thank you very much for reporting back!
The "latest" or versioned tag will be update with the next release.
