### ISSUE TITLE
Permission problem when installing Backblaze on Unraid

### ISSUE THREAD

**Issue by TherkelMJ** [JonathanTreffler/backblaze-personal-wine-container#108]
I'm having some problems with the backblaze_personal_backup docker on Unraid.
It looks like it doesn't have permissions to execute the exe file it downloads.
But when checking permissions for the "C-drive" where i assume it downloads it, i beleive it looks fine? 

root@ZeSmallOne:~# docker exec --user app backblaze_personal_backup ls -la /config/wine/dosdevices/
total 12
drwxr-xr-x 1 app app  12 Feb  2 18:41 .
drwxrwxrwx 1 app app 126 Feb  2 18:40 ..
lrwxrwxrwx 1 app app  10 Feb  2 18:39 c: -> ../drive_c
lrwxrwxrwx 1 app app   9 Feb  2 18:41 d: -> /drive_d/
lrwxrwxrwx 1 app app   1 Feb  2 18:39 z: -> /

____________________________________________________________________________________________________________________________________________
Log from the container

text  error  warn  system  array  login  

[init        ] giving control to process supervisor.
[supervisor  ] loading services...
[supervisor  ] loading service 'default'...
[supervisor  ] loading service 'app'...
[supervisor  ] loading service 'gui'...
[supervisor  ] loading service 'certsmonitor'...
[supervisor  ] loading service 'nginx'...
[supervisor  ] loading service 'xvnc'...
[supervisor  ] loading service 'openbox'...
[supervisor  ] loading service 'logmonitor'...
[supervisor  ] service 'logmonitor' is disabled.
[supervisor  ] loading service 'logrotate'...
[supervisor  ] all services loaded.
[supervisor  ] starting services...
[supervisor  ] starting service 'xvnc'...
[xvnc        ] Xvnc TigerVNC 1.13.1 - built Dec 21 2023 00:39:59
[xvnc        ] Copyright (C) 1999-2022 TigerVNC Team and many others (see README.rst)
[xvnc        ] See https://www.tigervnc.org for information on TigerVNC.
[xvnc        ] Underlying X server release 12014000
[xvnc        ] Fri Feb  2 18:48:39 2024
[xvnc        ]  vncext:      VNC extension running!
[xvnc        ]  vncext:      Listening for VNC connections on /tmp/vnc.sock (mode 0660)
[xvnc        ]  vncext:      created VNC server for screen 0
[supervisor  ] starting service 'nginx'...
[nginx       ] Listening for HTTPs connections on port 5800.
[supervisor  ] starting service 'openbox'...
[supervisor  ] starting service 'app'...
[app         ] + cat /RELEASE_VERSION
[app         ] + release_version=v1.6
[app         ] + local_version_file=/config/wine//dosdevices/c:/ProgramData/Backblaze/bzdata/bzreports/bzserv_version.txt
[app         ] + install_exe_path=/config/wine//dosdevices/c:/
[app         ] + log_file=/config/wine//dosdevices/c:/backblaze-wine-startapp.log
[app         ] + custom_user_agent=backblaze-personal-wine/v1.6 (JonathanTreffler, +https://github.com/JonathanTreffler/backblaze-personal-wine-container), CFNetwork
[app         ] + pinned_bz_version_file=/PINNED_BZ_VERSION
[app         ] + sed -n 1p /PINNED_BZ_VERSION
[app         ] + pinned_bz_version=9.0.0.749
[app         ] + sed -n 2p /PINNED_BZ_VERSION
[app         ] + pinned_bz_version_url=https://web.archive.org/web/20231218152237/https://secure.backblaze.com/win32/install_backblaze.exe
[app         ] + export WINEARCH=win64
[app         ] + disclaimer_updatemode
[app         ] + [ false = true ]
[app         ] + [ false = true ]
[app         ] + echo FORCE_LATEST_UPDATE is disabled. Using known-good version of Backblaze.
[app         ] FORCE_LATEST_UPDATE is disabled. Using known-good version of Backblaze.
[app         ] + [ -f /config/wine/drive_c/Program Files (x86)/Backblaze/bzbui.exe ]
[app         ] + mkdir -p /config/wine/
[app         ] + [ false = true ]
[app         ] + log_message INSTALLER: FORCE_LATEST_UPDATE=false, Installing pinned Backblaze version
[app         ] /startapp.sh: 159: log_message: not found
[app         ] + sleep infinity
[app         ] + curl -A backblaze-personal-wine/v1.6 (JonathanTreffler, +https://github.com/JonathanTreffler/backblaze-personal-wine-container), CFNetwork -L https://web.archive.org/web/20231218152237/https://secure.backblaze.com/win32/install_backblaze.exe --output install_backblaze.exe
[app         ]   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[app         ]                                  Dload  Upload   Total   Spent    Left  Speed
[app         ]   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[supervisor  ] all services started.
[app         ]   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[app         ]   0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
[xvnc        ] Fri Feb  2 18:48:43 2024
[xvnc        ]  Connections: accepted: /tmp/vnc.sock
[xvnc        ]  SConnection: Client needs protocol version 3.8
[xvnc        ]  SConnection: Client requests security type None(1)
[xvnc        ]  VNCSConnST:  Server default pixel format depth 24 (32bpp) little-endian rgb888
[xvnc        ]  VNCSConnST:  Client pixel format depth 24 (32bpp) little-endian bgr888
[xvnc        ]  ComparingUpdateTracker: 0 pixels in / 0 pixels out
[xvnc        ]  ComparingUpdateTracker: (1:-nan ratio)
[app         ]   0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
[app         ]   0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0Warning: Failed to create the file install_backblaze.exe: Permission denied
[app         ]   0 27.7M    0 13626    0     0   3556      0  2:16:29  0:00:03  2:16:26  3555
[app         ] curl: (23) Failed writing body (0 != 13626)
[xvnc        ] Fri Feb  2 18:48:54 2024
[xvnc        ]  VNCSConnST:  closing /tmp/vnc.sock: Clean disconnection
[xvnc        ]  EncodeManager: Framebuffer updates: 6
[xvnc        ]  EncodeManager:   Tight:
[xvnc        ]  EncodeManager:     Solid: 7 rects, 5.3272 Mpixels
[xvnc        ]  EncodeManager:            112 B (1:190258 ratio)
[xvnc        ]  EncodeManager:     Bitmap RLE: 1 rects, 160 pixels
[xvnc        ]  EncodeManager:                 68 B (1:9.58824 ratio)
[xvnc        ]  EncodeManager:   Total: 8 rects, 5.32736 Mpixels
[xvnc        ]  EncodeManager:          180 B (1:118386 ratio)
[xvnc        ]  Connections: closed: /tmp/vnc.sock
[xvnc        ]  ComparingUpdateTracker: 0 pixels in / 0 pixels out
[xvnc        ]  ComparingUpdateTracker: (1:-nan ratio)
[xvnc        ] Fri Feb  2 18:51:08 2024
[xvnc        ]  Connections: accepted: /tmp/vnc.sock
[xvnc        ]  SConnection: Client needs protocol version 3.8
[xvnc        ]  SConnection: Client requests security type None(1)
[xvnc        ]  VNCSConnST:  Server default pixel format depth 24 (32bpp) little-endian rgb888
[xvnc        ]  VNCSConnST:  Client pixel format depth 24 (32bpp) little-endian bgr888
[xvnc        ]  ComparingUpdateTracker: 0 pixels in / 0 pixels out
[xvnc        ]  ComparingUpdateTracker: (1:-nan ratio)

**Comment by johnnyfleet** [comment]
This sounds similar to what I'm troubleshooting in #81

**Comment by TherkelMJ** [comment]
> This sounds similar to what I'm troubleshooting in #81

Ye looks like you're right :)
Just tried setting USER_ID and GROUP_ID to 0, and then it works, so I guess it's purely a permission problem, and not a network problem.
Now i just got to find a user that isn't root, with permissions to run it

**Comment by traktuner** [comment]
> > This sounds similar to what I'm troubleshooting in #81
> 
> Ye looks like you're right :) Just tried setting USER_ID and GROUP_ID to 0, and then it works, so I guess it's purely a permission problem, and not a network problem. Now i just got to find a user that isn't root, with permissions to run it

Hello!
you are totally right, it's a permission issue. You can either create a totally new user just for backblaze on your system.
It has to have read-write permissions on the config folder where the container installs Backblaze to, and it need read-write permissions on all shares which you'd like to back up (Backblaze creates a .bzvol folder at the root of the shared folder / directory with infos that it can identify the drive and check its on/offline state).
Hope that helps!

**Comment by xela1** [comment]
I've submitted a pull request https://github.com/JonathanTreffler/backblaze-personal-wine-container/pull/110 that writes the download to /tmp rather than / when it's a new install (as well as fixing the log_message errors. 

If someone can review and approve the pull request, I believe these will solve the access denied issues without having to change USER_ID and GROUP_ID

**Comment by Brooklyn-Mark** [comment]
@traktuner @JonathanTreffler @xela1 I've commented in issue #81 that I wonder if this is due to unRAID not really having a user system like other distros for their docker system. They usually ask that dockers support PUID and PGID settings so that they can implement PUID (99) and PGID (100) in their templates so root doesn't need permissions.

**Comment by xela1** [comment]
@TherkelMJ can you test again with tessypowder/backblaze-personal-wine:ubuntu22 see if that stops the permission denied errors without changing user id

**Comment by kooori** [comment]
> @TherkelMJ can you test again with tessypowder/backblaze-personal-wine:ubuntu22 see if that stops the permission denied errors without changing user id

This fixed my issue!

**Comment by traktuner** [comment]
> > @TherkelMJ can you test again with tessypowder/backblaze-personal-wine:ubuntu22 see if that stops the permission denied errors without changing user id
> 
> This fixed my issue!

Glad it works for you now - thanks for reporting back!

**Comment by Brooklyn-Mark** [comment]
I would like to add that by using the ubuntu22 tag on unraid I can too access everything and backup fine now without adding UID and GID of 0. I am getting another issue of "your Backblaze client installation is not correct!" popup but I'll search the forums here to see if theres a thread for that since this thread is closed. Thanks!
