### ISSUE TITLE
Blank Screen and report from Backblaze of no backups for 15 days.

### ISSUE THREAD

**Issue by psyciknz** [JonathanTreffler/backblaze-personal-wine-container#114]
I have a notification email from backblaze today that my machine had no been backed up for 14 days.

I went to my UI, and I had a blank screen.   I did a pull and restarted the container, and it didn't seem to pull a new version.  But when container was up again there was a blank screen.

Here is a docker log: https://gist.github.com/psyciknz/849e2fdb9a9662ef4bbcf8ee21324288

I tried getting into the container and manually executing bzbui.exe but it complained that it wasn't owned by me.  I just wanted to manually trigger off the UI to see if I could get it.

I currently run: tessypowder/backblaze-personal-wine:latest

**Comment by psyciknz** [comment]
I use docker compose and so after reading the addition information, unsure how to set USER_ID=0 as per 
```
docker run \
    -p 8080:5800 \
    --init \
    --USER_ID=0 \
    --GROUP_ID=0 \
    --name backblaze_personal_backup \
    -v "[backup folder]/:/drive_d/" \
    -v "[config folder]/:/config/" \
    tessypowder/backblaze-personal-wine:latest
```

Did try running some of the other command and see these errors:
/hdd/docker-data/backblaze$ docker exec --user app backblaze wine explorer
Usage: update-mime-database [-hvVn] MIME-DIR
wine: Call from 771A19D7 to unimplemented function ole32.dll.OleInitialize, aborting
wine: Unimplemented function ole32.dll.OleInitialize called at address 771A19D7 (thread 011c), starting debugger...

**Comment by psyciknz** [comment]
I removed teh install_backblaze and can see this error:
[app         ] Warning: Failed to create the file install_backblaze.exe: Permission denied

the config dir is local on my host, and I've set the permissions to everyone rwx.  So not quite sure why that error is being thrown

**Comment by psyciknz** [comment]
Ok....so might have solved it.  Had to switch to the ubuntu22 image, and not latest.
Maybe there's something about the old ubuntu20 (on latest) that is not compatible any more.

**Comment by JeramieG-IDG** [comment]
im having the same issue with the same repository.  i'll try switching to ubuntu22 image as well.

**Comment by psyciknz** [comment]
> im having the same issue with the same repository. i'll try switching to ubuntu22 image as well.

I'm just re-attaching my backup, due to my playing I think I killed my install so it needed a new one.

**Comment by psyciknz** [comment]
> oh bummer, i've been trying to avoid that but might as well if I can't get it to work. Do you recall which ubuntu22 image you went with?

whatever is current today.
tessypowder/backblaze-personal-wine:ubuntu22

Unsure if you restart the container with a new image if it will retain everything, it may.   

I hosed the config/wine/program files (x86)\Backblaze dir on mine as part of trying to fix it....so it's no wonder I have to inherit the backup.  

But as long is the inherit works I'll be happy (rather than a full re-upload).

Good luck

**Comment by JeramieG-IDG** [comment]
Thankfully looks like that worked.

I changed it to :ubuntu22 waited for it to do its thing and its all good again.

Thanks for the help, hope yours goes well also.

**Comment by traktuner** [comment]
Hey,
Glad that it works again! Inherit should do it's thing and may take a while, yes - but I don't think that it would've been necessary here.
The Backblaze config folder should be by default locally on machine, so you can switch docker tags, etc and the Backblaze config files are untouched. If you change any files Backblaze needs, that's totally not recommended and you may end up re-doing your whole backup.
To be sure you got the latest image (when we push out non-versioned updates), you can also add `-rm` to your docker run command, which always deletes and re-downloads the docker image:

```
docker run \
    -rm \
    -p 8080:5800 \
    --init \
    --USER_ID=0 \
    --GROUP_ID=0 \
    --name backblaze_personal_backup \
    -v "[backup folder]/:/drive_d/" \
    -v "[config folder]/:/config/" \
    tessypowder/backblaze-personal-wine:latesta
```

**Comment by psyciknz** [comment]
So, it's been 14 hours, and the backup state is still inheriting....I suspect the account has timed out, as I see this message:
![image](https://github.com/JonathanTreffler/backblaze-personal-wine-container/assets/5350515/c9ce8faf-6386-4df6-9cec-b8329bd04dd8)

Unsure if there's anything that can be done to resolve that?

**Comment by traktuner** [comment]
> Unsure if there's anything that can be done to resolve that?

Have you already tried to restart the container? Inherit should continue (as you can restart your computer and the inherit continues if you have Backlaze installed on your PC/Mac)
It also depends on the size of your backup set - if it's not too large you can just re-do the initial backup.

**Comment by psyciknz** [comment]
yeah didn't seem to continue it.   I'm hoping if I keep moving the backblaze wndow it will figure I'm still there and keep me signed in.....the backup is pretty large..

**Comment by traktuner** [comment]
> yeah didn't seem to continue it. I'm hoping if I keep moving the backblaze wndow it will figure I'm still there and keep me signed in.....the backup is pretty large..

The error you see is - what I think - just that it tries to open a browser window.
Is the Backblaze app itself logged in? Do you see the inherit-progress bar?
You can also try to activate Virtual Desktop mode in Wine, then you have a task bar like in windows and can move / open / close windows:
Connect to the container via ssh
`docker exec -it backblaze-personal-wine-container bash`
then you can open wine config
`winecfg`
In the new window - `Graphics - Emulate a virtual desktop - Ok`
Maybe you can better troubleshoot with that

**Comment by psyciknz** [comment]
Cool, I've turned that on.   It's still progressing now that's I'm watching it.   Also btw, that command 
`docker exec -it --user app backblaze-personal-wine-container bash`
needs the user as well.  Else it complains about the owner.

And phew....it's completed inheriting finally.  Thanks

**Comment by traktuner** [comment]
> And phew....it's completed inheriting finally. Thanks

Yay, great to hear - thanks for letting me know!
I hope the backup continues without any issues :)
