### ISSUE TITLE
I get "WARNING your Backblaze installation is not correct!" popups when using the ubuntu22 tag on unRAID

### ISSUE THREAD

**Issue by Brooklyn-Mark** [JonathanTreffler/backblaze-personal-wine-container#116]
Hi,

I had to start using the ubuntu22 tag for the time being on unRAID to help get around the permissions issue which crept up there during the last update. Since then I've been getting this popup "WARNING your Backblaze installation is not correct!". Client is now uploading though.

It's an ominous warning but is it safe to ignore for now, or is there a way to fix it?

Thanks!

unRAID version 6.12.6 and backblaze-personal-wine-container docker container (from app store template) version :ubuntu22 pulled today

**Comment by traktuner** [comment]
Hey!
Could you please paste the full docker container logs here and let us know which Backlaze version is installed?
Also, please paste the log output from this file here: [your-config-folder]/dosdevices/c:/backblaze-wine-startapp.log
Thank you!

**Comment by Brooklyn-Mark** [comment]
Backblaze version 9.0.1.763

dosdevices log:
`Tue 23 Jan 2024 04:02:42 AM EST: UPDATER: FORCE_LATEST_UPDATE=false, Checking if newer version than /config/wine//dosdevices/c:/ProgramData/Backblaze/bzdata/bzreports/bzserv_version.txt is available.
Tue 23 Jan 2024 04:02:42 AM EST: UPDATER: COMPARE: no new version found - local 9.0.0.749 - remote 9.0.0.749
Tue 23 Jan 2024 04:02:42 AM EST: UPDATER: FORCE_LATEST_UPDATE=false, The local version is up to date. There may be a newer version available when using FORCE_LATEST_UPDATE=true
Tue 23 Jan 2024 04:02:42 AM EST: STARTAPP: Starting Backblaze version /config/wine//dosdevices/c:/ProgramData/Backblaze/bzdata/bzreports/bzserv_version.txt
Wed 24 Jan 2024 10:28:09 PM EST: UPDATER: FORCE_LATEST_UPDATE=false, Checking if newer version than /config/wine//dosdevices/c:/ProgramData/Backblaze/bzdata/bzreports/bzserv_version.txt is available.
Wed 24 Jan 2024 10:28:09 PM EST: UPDATER: COMPARE: no new version found - local 9.0.0.749 - remote 9.0.0.749
Wed 24 Jan 2024 10:28:09 PM EST: UPDATER: FORCE_LATEST_UPDATE=false, The local version is up to date. There may be a newer version available when using FORCE_LATEST_UPDATE=true
Wed 24 Jan 2024 10:28:09 PM EST: STARTAPP: Starting Backblaze version /config/wine//dosdevices/c:/ProgramData/Backblaze/bzdata/bzreports/bzserv_version.txt
Thu 25 Jan 2024 04:37:47 AM EST: UPDATER: FORCE_LATEST_UPDATE=false, Checking if newer version than /config/wine//dosdevices/c:/ProgramData/Backblaze/bzdata/bzreports/bzserv_version.txt is available.
Thu 25 Jan 2024 04:37:47 AM EST: UPDATER: COMPARE: no new version found - local 9.0.0.749 - remote 9.0.0.749
Thu 25 Jan 2024 04:37:47 AM EST: UPDATER: FORCE_LATEST_UPDATE=false, The local version is up to date. There may be a newer version available when using FORCE_LATEST_UPDATE=true
Thu 25 Jan 2024 04:37:47 AM EST: STARTAPP: Starting Backblaze version /config/wine//dosdevices/c:/ProgramData/Backblaze/bzdata/bzreports/bzserv_version.txt
Thu 25 Jan 2024 08:37:00 AM EST: UPDATER: FORCE_LATEST_UPDATE=false, Checking if newer version than /config/wine//dosdevices/c:/ProgramData/Backblaze/bzdata/bzreports/bzserv_version.txt is available.
Thu 25 Jan 2024 08:37:00 AM EST: UPDATER: COMPARE: no new version found - local 9.0.0.749 - remote 9.0.0.749
Thu 25 Jan 2024 08:37:00 AM EST: UPDATER: FORCE_LATEST_UPDATE=false, The local version is up to date. There may be a newer version available when using FORCE_LATEST_UPDATE=true
Thu 25 Jan 2024 08:37:00 AM EST: STARTAPP: Starting Backblaze version /config/wine//dosdevices/c:/ProgramData/Backblaze/bzdata/bzreports/bzserv_version.txt
Thu 01 Feb 2024 04:38:13 AM EST: UPDATER: FORCE_LATEST_UPDATE=false, Checking if newer version than /config/wine//dosdevices/c:/ProgramData/Backblaze/bzdata/bzreports/bzserv_version.txt is available.
Thu 01 Feb 2024 04:38:13 AM EST: UPDATER: COMPARE: no new version found - local 9.0.0.749 - remote 9.0.0.749
Thu 01 Feb 2024 04:38:13 AM EST: UPDATER: FORCE_LATEST_UPDATE=false, The local version is up to date. There may be a newer version available when using FORCE_LATEST_UPDATE=true
Thu 01 Feb 2024 04:38:13 AM EST: STARTAPP: Starting Backblaze version /config/wine//dosdevices/c:/ProgramData/Backblaze/bzdata/bzreports/bzserv_version.txt
Mon 05 Feb 2024 09:27:52 AM EST: UPDATER: FORCE_LATEST_UPDATE=false, Checking if newer version than /config/wine//dosdevices/c:/ProgramData/Backblaze/bzdata/bzreports/bzserv_version.txt is available.
Mon 05 Feb 2024 09:27:52 AM EST: UPDATER: COMPARE: no new version found - local 9.0.0.749 - remote 9.0.0.749
Mon 05 Feb 2024 09:27:52 AM EST: UPDATER: FORCE_LATEST_UPDATE=false, The local version is up to date. There may be a newer version available when using FORCE_LATEST_UPDATE=true
Mon 05 Feb 2024 09:27:52 AM EST: STARTAPP: Starting Backblaze version /config/wine//dosdevices/c:/ProgramData/Backblaze/bzdata/bzreports/bzserv_version.txt
Mon 05 Feb 2024 09:44:53 AM EST: UPDATER: FORCE_LATEST_UPDATE=false, Checking if newer version than /config/wine//dosdevices/c:/ProgramData/Backblaze/bzdata/bzreports/bzserv_version.txt is available.
Mon 05 Feb 2024 09:44:53 AM EST: UPDATER: COMPARE: no new version found - local 9.0.0.749 - remote 9.0.0.749
Mon 05 Feb 2024 09:44:53 AM EST: UPDATER: FORCE_LATEST_UPDATE=false, The local version is up to date. There may be a newer version available when using FORCE_LATEST_UPDATE=true
Mon 05 Feb 2024 09:44:53 AM EST: STARTAPP: Starting Backblaze version /config/wine//dosdevices/c:/ProgramData/Backblaze/bzdata/bzreports/bzserv_version.txt
Mon 05 Feb 2024 09:53:29 AM EST: UPDATER: FORCE_LATEST_UPDATE=false, Checking if newer version than /config/wine//dosdevices/c:/ProgramData/Backblaze/bzdata/bzreports/bzserv_version.txt is available.
Mon 05 Feb 2024 09:53:29 AM EST: UPDATER: COMPARE: no new version found - local 9.0.0.749 - remote 9.0.0.749
Mon 05 Feb 2024 09:53:29 AM EST: UPDATER: FORCE_LATEST_UPDATE=false, The local version is up to date. There may be a newer version available when using FORCE_LATEST_UPDATE=true
Mon 05 Feb 2024 09:53:29 AM EST: STARTAPP: Starting Backblaze version /config/wine//dosdevices/c:/ProgramData/Backblaze/bzdata/bzreports/bzserv_version.txt
Mon 05 Feb 2024 09:54:18 AM EST: UPDATER: FORCE_LATEST_UPDATE=false, Checking if newer version than /config/wine//dosdevices/c:/ProgramData/Backblaze/bzdata/bzreports/bzserv_version.txt is available.
Mon 05 Feb 2024 09:54:18 AM EST: UPDATER: COMPARE: no new version found - local 9.0.0.749 - remote 9.0.0.749
Mon 05 Feb 2024 09:54:18 AM EST: UPDATER: FORCE_LATEST_UPDATE=false, The local version is up to date. There may be a newer version available when using FORCE_LATEST_UPDATE=true
Mon 05 Feb 2024 09:54:18 AM EST: STARTAPP: Starting Backblaze version /config/wine//dosdevices/c:/ProgramData/Backblaze/bzdata/bzreports/bzserv_version.txt
Mon 05 Feb 2024 10:03:09 AM EST: UPDATER: FORCE_LATEST_UPDATE=false, Checking if newer version than /config/wine//dosdevices/c:/ProgramData/Backblaze/bzdata/bzreports/bzserv_version.txt is available.
Mon 05 Feb 2024 10:03:09 AM EST: UPDATER: COMPARE: no new version found - local 9.0.0.749 - remote 9.0.0.749
Mon 05 Feb 2024 10:03:09 AM EST: UPDATER: FORCE_LATEST_UPDATE=false, The local version is up to date. There may be a newer version available when using FORCE_LATEST_UPDATE=true
Mon 05 Feb 2024 10:03:09 AM EST: STARTAPP: Starting Backblaze version /config/wine//dosdevices/c:/ProgramData/Backblaze/bzdata/bzreports/bzserv_version.txt
Mon 05 Feb 2024 10:17:05 AM EST: UPDATER: FORCE_LATEST_UPDATE=false, Checking if newer version than /config/wine//dosdevices/c:/ProgramData/Backblaze/bzdata/bzreports/bzserv_version.txt is available.
Mon 05 Feb 2024 10:17:05 AM EST: UPDATER: COMPARE: no new version found - local 9.0.0.749 - remote 9.0.0.749
Mon 05 Feb 2024 10:17:05 AM EST: UPDATER: FORCE_LATEST_UPDATE=false, The local version is up to date. There may be a newer version available when using FORCE_LATEST_UPDATE=true
Mon 05 Feb 2024 10:17:05 AM EST: STARTAPP: Starting Backblaze version /config/wine//dosdevices/c:/ProgramData/Backblaze/bzdata/bzreports/bzserv_version.txt
Mon Feb  5 10:21:39 AM EST 2024: UPDATER: FORCE_LATEST_UPDATE=false, Checking if newer version than /config/wine//dosdevices/c:/ProgramData/Backblaze/bzdata/bzreports/bzserv_version.txt is available.
Mon Feb  5 10:21:39 AM EST 2024: UPDATER: COMPARE: newer version found - local 9.0.0.749 - remote 9.0.1.763
Mon Feb  5 10:21:39 AM EST 2024: UPDATER: FORCE_LATEST_UPDATE=false, Newer version found - downloading and installing the newer version...
Mon Feb  5 10:21:39 AM EST 2024: UPDATER: FORCE_LATEST_UPDATE=false - downloading known-good version from archive.org
Mon Feb  5 10:22:07 AM EST 2024: UPDATER: Starting install_backblaze.exe
Mon Feb  5 11:28:24 AM EST 2024: UPDATER: FORCE_LATEST_UPDATE=false, Checking if newer version than /config/wine//dosdevices/c:/ProgramData/Backblaze/bzdata/bzreports/bzserv_version.txt is available.
Mon Feb  5 11:28:24 AM EST 2024: UPDATER: COMPARE: no new version found - local 9.0.1.763 - remote 9.0.1.763
Mon Feb  5 11:28:24 AM EST 2024: UPDATER: FORCE_LATEST_UPDATE=false, The local version is up to date. There may be a newer version available when using FORCE_LATEST_UPDATE=true
Mon Feb  5 11:28:24 AM EST 2024: STARTAPP: Starting Backblaze version 9.0.1.763
Mon Feb  5 11:34:04 AM EST 2024: UPDATER: FORCE_LATEST_UPDATE=false, Checking if newer version than /config/wine//dosdevices/c:/ProgramData/Backblaze/bzdata/bzreports/bzserv_version.txt is available.
Mon Feb  5 11:34:04 AM EST 2024: UPDATER: COMPARE: no new version found - local 9.0.1.763 - remote 9.0.1.763
Mon Feb  5 11:34:04 AM EST 2024: UPDATER: FORCE_LATEST_UPDATE=false, The local version is up to date. There may be a newer version available when using FORCE_LATEST_UPDATE=true
Mon Feb  5 11:34:04 AM EST 2024: STARTAPP: Starting Backblaze version 9.0.1.763
Mon Feb  5 11:37:04 AM EST 2024: UPDATER: FORCE_LATEST_UPDATE=false, Checking if newer version than /config/wine//dosdevices/c:/ProgramData/Backblaze/bzdata/bzreports/bzserv_version.txt is available.
Mon Feb  5 11:37:04 AM EST 2024: UPDATER: COMPARE: no new version found - local 9.0.1.763 - remote 9.0.1.763
Mon Feb  5 11:37:04 AM EST 2024: UPDATER: FORCE_LATEST_UPDATE=false, The local version is up to date. There may be a newer version available when using FORCE_LATEST_UPDATE=true
Mon Feb  5 11:37:04 AM EST 2024: STARTAPP: Starting Backblaze version 9.0.1.763
Mon Feb  5 11:39:23 AM EST 2024: UPDATER: FORCE_LATEST_UPDATE=false, Checking if newer version than /config/wine//dosdevices/c:/ProgramData/Backblaze/bzdata/bzreports/bzserv_version.txt is available.
Mon Feb  5 11:39:23 AM EST 2024: UPDATER: COMPARE: no new version found - local 9.0.1.763 - remote 9.0.1.763
Mon Feb  5 11:39:23 AM EST 2024: UPDATER: FORCE_LATEST_UPDATE=false, The local version is up to date. There may be a newer version available when using FORCE_LATEST_UPDATE=true
Mon Feb  5 11:39:23 AM EST 2024: STARTAPP: Starting Backblaze version 9.0.1.763
Mon Feb  5 11:50:56 AM EST 2024: UPDATER: FORCE_LATEST_UPDATE=true, updating to the latest version
Mon Feb  5 11:50:57 AM EST 2024: UPDATER: COMPARE: no new version found - local 9.0.1.763 - remote 9.0.1.763
Mon Feb  5 11:50:57 AM EST 2024: UPDATER: The installed version is up to date.
Mon Feb  5 11:50:57 AM EST 2024: STARTAPP: Starting Backblaze version 9.0.1.763
Thu Feb  8 04:04:15 AM EST 2024: UPDATER: FORCE_LATEST_UPDATE=true, checking for a new version
Thu Feb  8 04:04:16 AM EST 2024: UPDATER: Installed Version=9.0.1.763
Thu Feb  8 04:04:16 AM EST 2024: UPDATER: Latest Version=9.0.1.763
Thu Feb  8 04:04:16 AM EST 2024: UPDATER: The installed version is up to date.
Thu Feb  8 04:04:16 AM EST 2024: STARTAPP: Starting Backblaze version 9.0.1.763
Thu Feb  8 04:38:16 AM EST 2024: UPDATER: FORCE_LATEST_UPDATE=true, checking for a new version
Thu Feb  8 04:38:17 AM EST 2024: UPDATER: Installed Version=9.0.1.763
Thu Feb  8 04:38:17 AM EST 2024: UPDATER: Latest Version=9.0.1.763
Thu Feb  8 04:38:17 AM EST 2024: UPDATER: The installed version is up to date.
Thu Feb  8 04:38:17 AM EST 2024: STARTAPP: Starting Backblaze version 9.0.1.763
Fri Feb  9 12:23:02 PM EST 2024: UPDATER: FORCE_LATEST_UPDATE=true, checking for a new version
Fri Feb  9 12:23:03 PM EST 2024: UPDATER: Installed Version=9.0.1.763
Fri Feb  9 12:23:03 PM EST 2024: UPDATER: Latest Version=9.0.1.763
Fri Feb  9 12:23:03 PM EST 2024: UPDATER: The installed version is up to date.
Fri Feb  9 12:23:03 PM EST 2024: STARTAPP: Starting Backblaze version 9.0.1.763
Sat Feb 10 09:33:17 AM EST 2024: UPDATER: FORCE_LATEST_UPDATE=true, checking for a new version
Sat Feb 10 09:33:18 AM EST 2024: UPDATER: Installed Version=9.0.1.763
Sat Feb 10 09:33:18 AM EST 2024: UPDATER: Latest Version=9.0.1.763
Sat Feb 10 09:33:18 AM EST 2024: UPDATER: The installed version is up to date.
Sat Feb 10 09:33:18 AM EST 2024: STARTAPP: Starting Backblaze version 9.0.1.763
Sat Feb 10 11:20:41 AM EST 2024: UPDATER: FORCE_LATEST_UPDATE=false
Sat Feb 10 11:20:41 AM EST 2024: UPDATER: Installed Version=9.0.1.763
Sat Feb 10 11:20:41 AM EST 2024: UPDATER: Pinned Version=9.0.1.763
Sat Feb 10 11:20:41 AM EST 2024: UPDATER: Installed version is up to date. There may be a newer version available when using FORCE_LATEST_UPDATE=true
Sat Feb 10 11:20:41 AM EST 2024: STARTAPP: Starting Backblaze version 9.0.1.763
Sat Feb 10 11:45:34 AM EST 2024: UPDATER: FORCE_LATEST_UPDATE=false
Sat Feb 10 11:45:34 AM EST 2024: UPDATER: Installed Version=9.0.1.763
Sat Feb 10 11:45:34 AM EST 2024: UPDATER: Pinned Version=9.0.1.763
Sat Feb 10 11:45:34 AM EST 2024: UPDATER: Installed version is up to date. There may be a newer version available when using FORCE_LATEST_UPDATE=true
Sat Feb 10 11:45:34 AM EST 2024: STARTAPP: Starting Backblaze version 9.0.1.763
Sat Feb 10 11:46:28 AM EST 2024: UPDATER: FORCE_LATEST_UPDATE=false
Sat Feb 10 11:46:28 AM EST 2024: UPDATER: Installed Version=9.0.1.763
Sat Feb 10 11:46:28 AM EST 2024: UPDATER: Pinned Version=9.0.1.763
Sat Feb 10 11:46:28 AM EST 2024: UPDATER: Installed version is up to date. There may be a newer version available when using FORCE_LATEST_UPDATE=true
Sat Feb 10 11:46:28 AM EST 2024: STARTAPP: Starting Backblaze version 9.0.1.763
Sun Feb 11 08:02:12 AM EST 2024: UPDATER: FORCE_LATEST_UPDATE=false
Sun Feb 11 08:02:12 AM EST 2024: UPDATER: Installed Version=9.0.1.763
Sun Feb 11 08:02:12 AM EST 2024: UPDATER: Pinned Version=9.0.1.763
Sun Feb 11 08:02:12 AM EST 2024: UPDATER: Installed version is up to date. There may be a newer version available when using FORCE_LATEST_UPDATE=true
Sun Feb 11 08:02:12 AM EST 2024: STARTAPP: Starting Backblaze version 9.0.1.763
`
docker container log copied from console of unRAID. Not sure where the full logs are kept. Please advise if this isn't enough: 
`text  error  warn  system  array  login  

[app         ] ++ sed -n 1p /PINNED_BZ_VERSION
[app         ] + pinned_bz_version=9.0.1.763
[app         ] ++ sed -n 2p /PINNED_BZ_VERSION
[app         ] + pinned_bz_version_url=https://web.archive.org/web/20240126203244/https://secure.backblaze.com/win32/install_backblaze.exe
[app         ] + export WINEARCH=win64
[app         ] + WINEARCH=win64
[app         ] + disclaimer_updatemode
[app         ] + '[' false = true ']'
[app         ] + '[' false = true ']'
[app         ] + echo 'FORCE_LATEST_UPDATE is disabled. Using known-good version of Backblaze.'
[app         ] FORCE_LATEST_UPDATE is disabled. Using known-good version of Backblaze.
[app         ] + '[' '!' -d /config/wine/ ']'
[app         ] + for x in {d..z}
[app         ] + test -d /drive_d
[app         ] + test -d /config/wine/dosdevices/d:
[app         ] + for x in {d..z}
[app         ] + test -d /drive_e
[app         ] + for x in {d..z}
[app         ] + test -d /drive_f
[app         ] + for x in {d..z}
[app         ] + test -d /drive_g
[app         ] + for x in {d..z}
[app         ] + test -d /drive_h
[app         ] + for x in {d..z}
[app         ] + test -d /drive_i
[app         ] + for x in {d..z}
[app         ] + test -d /drive_j
[app         ] + for x in {d..z}
[app         ] + test -d /drive_k
[app         ] + for x in {d..z}
[app         ] + test -d /drive_l
[app         ] + for x in {d..z}
[app         ] + test -d /drive_m
[app         ] + for x in {d..z}
[app         ] + test -d /drive_n
[app         ] + for x in {d..z}
[app         ] + test -d /drive_o
[app         ] + for x in {d..z}
[app         ] + test -d /drive_p
[app         ] + for x in {d..z}
[app         ] + test -d /drive_q
[app         ] + for x in {d..z}
[app         ] + test -d /drive_r
[app         ] + for x in {d..z}
[app         ] + test -d /drive_s
[app         ] + for x in {d..z}
[app         ] + test -d /drive_t
[app         ] + for x in {d..z}
[app         ] + test -d /drive_u
[app         ] + for x in {d..z}
[app         ] + test -d /drive_v
[app         ] + for x in {d..z}
[app         ] + test -d /drive_w
[app         ] + for x in {d..z}
[app         ] + test -d /drive_x
[app         ] + for x in {d..z}
[app         ] + test -d /drive_y
[app         ] + for x in {d..z}
[app         ] + test -d /drive_z
[app         ] + '[' -f '/config/wine/drive_c/Program Files (x86)/Backblaze/bzbui.exe' ']'
[app         ] + '[' false = true ']'
[app         ] + '[' false = true ']'
[app         ] + '[' -f /config/wine/dosdevices/c:/ProgramData/Backblaze/bzdata/bzreports/bzserv_version.txt ']'
[app         ] ++ cat /config/wine/dosdevices/c:/ProgramData/Backblaze/bzdata/bzreports/bzserv_version.txt
[app         ] + local_version=9.0.1.763
[app         ] + log_message 'UPDATER: FORCE_LATEST_UPDATE=false'
[app         ] ++ date
[app         ] + echo 'Sun Feb 11 08:02:12 AM EST 2024: UPDATER: FORCE_LATEST_UPDATE=false'
[app         ] + log_message 'UPDATER: Installed Version=9.0.1.763'
[app         ] ++ date
[app         ] + echo 'Sun Feb 11 08:02:12 AM EST 2024: UPDATER: Installed Version=9.0.1.763'
[app         ] + log_message 'UPDATER: Pinned Version=9.0.1.763'
[app         ] ++ date
[app         ] + echo 'Sun Feb 11 08:02:12 AM EST 2024: UPDATER: Pinned Version=9.0.1.763'
[app         ] + compare_versions 9.0.1.763 9.0.1.763
[app         ] + local_version=9.0.1.763
[app         ] + compare_version=9.0.1.763
[app         ] + dpkg --compare-versions 9.0.1.763 lt 9.0.1.763
[app         ] + return 1
[app         ] + log_message 'UPDATER: Installed version is up to date. There may be a newer version available when using FORCE_LATEST_UPDATE=true'
[app         ] ++ date
[app         ] + echo 'Sun Feb 11 08:02:12 AM EST 2024: UPDATER: Installed version is up to date. There may be a newer version available when using FORCE_LATEST_UPDATE=true'
[app         ] + start_app
[app         ] ++ cat /config/wine/dosdevices/c:/ProgramData/Backblaze/bzdata/bzreports/bzserv_version.txt
[app         ] + log_message 'STARTAPP: Starting Backblaze version 9.0.1.763'
[app         ] ++ date
[app         ] + echo 'Sun Feb 11 08:02:12 AM EST 2024: STARTAPP: Starting Backblaze version 9.0.1.763'
[app         ] + sleep infinity
[app         ] + wine64 '/config/wine/drive_c/Program Files (x86)/Backblaze/bzbui.exe' -noquiet
[supervisor  ] all services started.
`

Thanks!

**Comment by xela1** [comment]
Did this occur right after the last upgrade of the client?

**Comment by Brooklyn-Mark** [comment]
@xela1 yes. I think so. I set force update to "true" when I was having those issues with permissions and the black screen, but then when I was finally able to get back into backblaze with backups working, this popup kept showing. As I said, backup seem to be working (haven't tried to restore) but just annoying popup that's a bit ominous.

**Comment by Brooklyn-Mark** [comment]
@xela1 I think there was an error in the path you referenced above "dosservices" was in `[your-config-folder]/wine/dosdevices/...` so I added that in. Once I did that it did re-install and I'm not getting this pop-up now. Thanks.

Only problem is I'm getting a permission issue popup for "C:|ProgramData\Backblaze|bzdata\bzreports" inside the container. Again backups are running fine. Any insight?

**Comment by traktuner** [comment]
> @xela1 I think there was an error in the path you referenced above "dosservices" was in `[your-config-folder]/wine/dosdevices/...` so I added that in. Once I did that it did re-install and I'm not getting this pop-up now. Thanks.
> 
> Only problem is I'm getting a permission issue popup for "C:|ProgramData\Backblaze|bzdata\bzreports" inside the container. Again backups are running fine. Any insight?

The error you mentioned above in your issue is in fact a problem with the Backblaze installation itself:
https://www.reddit.com/r/backblaze/comments/1645802/comment/jy6t84o/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
Good that it's now fixed with a re-install!

You can ignore the bzreports permission issue.
Permissions are correct, but Backblaze is not made for running in a docker container which involves different permission sets. I have this error since the initial release of this project (I'm on Synology) and never had any backup/restore problems. I do a restore test with many random files every few months.

**Comment by Brooklyn-Mark** [comment]
Gotcha. Thanks @traktuner for clearing this up! @xela1 thanks for helping me manually reinstall.

Closing the issue now.

**Comment by traktuner** [comment]
@xela1 I already startet that yesterday, but then I thought that it's better to document the manual reinstall process (which is fairly easy) only in the readme.
That particular issue with a faulty Backblaze installation is too rare to justify a dedicated function in the codebase (which needs to be maintained, too)

**Comment by devanteweary** [comment]
> You can ignore the bzreports permission issue. Permissions are correct, but Backblaze is not made for running in a docker container which involves different permission sets. I have this error since the initial release of this project (I'm on Synology) and never had any backup/restore problems. I do a restore test with many random files every few months.

Hey @traktuner , just wondering if you have any methodology when you do restore tests.
Like do you make sure to do certain file sizes, etc?

**Comment by traktuner** [comment]
> Hey @traktuner , just wondering if you have any methodology when you do restore tests. Like do you make sure to do certain file sizes, etc?
Hey,
no, everything is a random selection. I usually do that on a quaterly basis and always use different historical timeframes.
Like, going back in the timeline 9 monts ago, opening up a folder, selecting a few files, and so on, all from that date.
And so I have maybe only a few 10MB to maybe 100GB of files to restore, debending on the random folders I select.
With the new built-in bzrestore app this is very easy.
It should of course be a managable amount of files since you then have to verify if the files are intact 😅
