### ISSUE TITLE
What is normal RAM usage

### ISSUE THREAD

**Issue by MervisDiamonds** [JonathanTreffler/backblaze-personal-wine-container#12]
I tried to put this in discussion but it wouldn't post.....

How much RAM is your container using?  While performing an initial backup, usage increased to 5GB.  I restarted the container and now it it is at 200mb and steady climbing.

**Comment by JonathanTreffler** [comment]
My docker with an uptime of 13 days uses 4,5 GB of RAM. My server has 32Gb of RAM, so i honestly didn't even notice, but that does seem quite high.
But maybe that is normal for the Backblaze Backup Client 🤷‍♂️.
There is a potential memory leak if you forgot the --init parameter in the docker run command.
But that does not explain the 4,5 Gb of my setup, as i have that set correctly.

**Comment by MervisDiamonds** [comment]
I have a similar set up regarding --int and 32GB RAM. Good to know that is normal.
