### ISSUE TITLE
Solid blue screen since update

### ISSUE THREAD

**Issue by wormvortex** [JonathanTreffler/backblaze-personal-wine-container#121]
Since updating yesterday my Backblaze is just a permanent blue screen. I can see and move the remote cursor but that is all.

Any ideas of how to fix this?

**Comment by bmccord** [comment]
Same here. Hopefully there will be a solution soon.

**Comment by xela1** [comment]
Please post container logs so people might be able to help you

**Comment by wormvortex** [comment]
Here's my most recent logs:


[backblaze_personal_backup-2024-02-14T23-40-21.log](https://github.com/JonathanTreffler/backblaze-personal-wine-container/files/14289628/backblaze_personal_backup-2024-02-14T23-40-21.log)

**Comment by traktuner** [comment]
Hey,
with v1.7 we turned on Wine's virtual desktop feature by default. What you'll see is the "background".
It seems that your resolution defaulted to 1920x1080 which is very high, need to fix that in a future update.
But you should have scroll bars in your browser. Scroll to the bottom, the Backblaze installer (auto-update) should be in the task bar. Do a right click on it and click "Restore" then the updater should be visible. Click on install and then the Backblaze UI should start automatically.

**Comment by wormvortex** [comment]
I can't see any scroll bars on mine. When I go to view it on my phone as well I can see the entire screen and there's no bars ![image](https://github.com/JonathanTreffler/backblaze-personal-wine-container/assets/82380589/72834001-8575-402d-a169-ad7cc01c318e)

**Comment by traktuner** [comment]
> I can't see any scroll bars on mine. When I go to view it on my phone as well I can see the entire screen and there's no bars

Hey @wormvortex 
I just pushed out v1.7.1 - please use this version. I am still not sure if you really see the whole screen. It should have a bar (like the windows start bar) at the bottom.
Also, please send the full docker logs of the container, and the backblaze-wine-startapp.log which should be located here:
[your-config-folder]/dosdevices/c:/backblaze-wine-startapp.log
Thank you!

**Comment by wormvortex** [comment]
Updated it and could see the taskbar at the bottom this time and the new versions installed and running. It did pop up about a permission issue accessing something on c:/ but I accidentally closed it before taking note of the error.

I've also attached the startapp.log

[backblaze-wine-startapp.log](https://github.com/JonathanTreffler/backblaze-personal-wine-container/files/14299015/backblaze-wine-startapp.log)

**Comment by traktuner** [comment]
Great to hear!
The error is probably a permission error with the bzreports directory. It can read and write to it when Backblaze can back up files. So you can ignore it.
