### ISSUE TITLE
Issue after latest update

### ISSUE THREAD

**Issue by solace666** [JonathanTreffler/backblaze-personal-wine-container#123]
Everything starts and seems to back up ok but I get a pop up that says:

WARNING: your Backblaze client installation is not correct!
Check your logs and download and install a new client from the Backblaze website.

Any ideas?

Thanks.

**Comment by traktuner** [comment]
Hey,
you can try to force a reinstall of the client, that should fix your issue.
Described here:
https://github.com/JonathanTreffler/backblaze-personal-wine-container/issues/116#issuecomment-1941602719
However, the path starts with [your-config-folder]/wine/dosdevices/... (wine is missing in the comment)

**Comment by solace666** [comment]
I did the above and now the "wine" window just shows a "bzinst_win32_self_extract..." window at the bottom.

**Comment by solace666** [comment]
It took a very long time but the install window finally came up.  I'm all good now.  Thanks.
