### ISSUE TITLE
Stuck at "bzinst_win32_self_extract..."

### ISSUE THREAD

**Issue by newoski** [JonathanTreffler/backblaze-personal-wine-container#124]
![image](https://github.com/JonathanTreffler/backblaze-personal-wine-container/assets/13788074/6ba32e75-0280-4863-957f-104718aa340d)

No matter which version I try to install now, I get stuck at the bzinst_win32_self_extract...

I have tried leaving my system overnight, just to make sure it wasn't something I needed to wait out, but it just sits at this screen forever

**Comment by traktuner** [comment]
Does a right click, clicking "Move" or "Restore" and another click on bzinst... reveal the installer?

**Comment by newoski** [comment]
Not sure how to right click within the docker UI window. Doesn't seem to
work. Right clicks only register on my PC, not the docker UI

**Comment by traktuner** [comment]
Hey @newoski,
everything you see in your browser, like the Backblaze UI, the "Start" button etc should be clickable with your mouse.
You should be able to click on the blue, minimized bzinst_... bar in your screenshot. When you do a right click, in the quick menu you have the options "Move" and "Restore". Click on any of those and try a few things if the installer window comes up.
If that does not work, you may have an inssue with your browser.

**Comment by newoski** [comment]
> Hey @newoski, everything you see in your browser, like the Backblaze UI, the "Start" button etc should be clickable with your mouse. You should be able to click on the blue, minimized bzinst_... bar in your screenshot. When you do a right click, in the quick menu you have the options "Move" and "Restore". Click on any of those and try a few things if the installer window comes up. If that does not work, you may have an inssue with your browser.

Thanks for the replies. While I wasn't able to get right clicking working -- while accessing my Unraid Docker via my web browser on my Windows 10 PC -- I was able to get the docker going, finally. It looks like it just took forever to initially extract the files for some reason. Everything is working now, including inheriting my previous backup.
