### ISSUE TITLE
Permissions issues in logs 

### ISSUE THREAD

**Issue by psiberfunk** [JonathanTreffler/backblaze-personal-wine-container#125]
Despite apparently working fine and actually backing up files, my setup is somehow spewing lots of errors into the docker logs like these, with hundreds of lines per minute... I cannot figure out what's going wrong.. the mapped drives are accessible inside the explorer.exe interface inside the web-vnc client, and I know I can even open some test files in notepad.exe.

Any hints as to what's misconfigured from a stream of errors like this ?

<img width="953" alt="Screenshot 2024-02-17 at 10 49 57 AM" src="https://github.com/JonathanTreffler/backblaze-personal-wine-container/assets/19777571/550f8ecf-d5fa-4798-9f6a-e23ae9a34ffd">

Restarting / resetting the container doesn't seem to do much, and i'm on the latest main image:

<img width="790" alt="Screenshot 2024-02-17 at 10 51 33 AM" src="https://github.com/JonathanTreffler/backblaze-personal-wine-container/assets/19777571/225202ce-4b5a-4e14-b29b-a2f33718b4ad">

**Comment by traktuner** [comment]
Hey @psiberfunk 
Please have a look at our troubleshooting section
https://github.com/JonathanTreffler/backblaze-personal-wine-container?tab=readme-ov-file#troubleshooting
There is a specific part for Synology at the bottom.

**Comment by psiberfunk** [comment]
@traktuner : I should have mentioned, I am already running it with elevated permissions. I have seen that part of the troubleshooting and tried it and it does not seem to fix the issue

**Comment by traktuner** [comment]
Thank you!
Could you please post your full docker run command, or screenshots from the container manager with all environment variables?
Also the full docker logs. 
Is USER_ID=0 and GROUP_ID=0 set according to the docs? 
I am also using a Synology setup and it only works with those variables set. 
Thank you!

**Comment by psiberfunk** [comment]
Well, I ran into some unrelated issues and decided to start over completely from scratch using the Syno Container with the intent of just inheriting my existing backup on BB....  and now i'm having even MORE trouble, not getting the installer to run... looks like from logs it's downloading but that it won't show up on VNC. 

 ==> Halp, i've gone backwards !!

**My Setup:**

- Synology 921+ using native Container Manager App (also have portainer, but for simplicity of replication, using native app here).
- Config Folder location:   _/docker/backblazeContainer_

**Steps**

1. Blow away the container, image, and the docker /config folder to reset everything to scratch.
2. Pull **main** image from dockerhub. "Run" (create new container), with following changes before firstime run:

- Set mem limit to 8 GB, Enable autorestart
- Map port 5800 to external 8800

Alter the following environment variables:   
- USER_ID,GROUP_ID = 0 ,   
- Deleted blank values b/c the syno app complains if left blank (deleted:  SUP_GROUP_IDS,INSTALL_PACKAGES,PACKAGES_MIRROR)
- Set VNC_PASSWORD
- Set Execute container using high privilege

Setup drives (all as r/w):
- /config --> /docker/backblazeContainer
- /drive_m --> /music
- /drive_x  -->  xxxxxxxx  (etc, for each drive I wanted)

See config zip JSON here, password redacted:
[tessypowder-backblaze-personal-wine.json.zip](https://github.com/JonathanTreffler/backblaze-personal-wine-container/files/14324318/tessypowder-backblaze-personal-wine.json.zip)

3. Start container, login to VNC (successfully)
4. Observe that it downloads the installer fine in logs.. says running installer EXE in logs. Wait.. and wait... stare at this image in my VNC... **and ... nothing happens?**

<img width="910" alt="Screenshot 2024-02-18 at 3 27 09 PM" src="https://github.com/JonathanTreffler/backblaze-personal-wine-container/assets/19777571/28a1f7fc-6c43-420b-8db1-5853d0c539d0">

Docker Logs, CSV format:  

[tessypowder-backblaze-personal-wine_Logs.csv.zip](https://github.com/JonathanTreffler/backblaze-personal-wine-container/files/14324335/tessypowder-backblaze-personal-wine_Logs.csv.zip)

**Comment by traktuner** [comment]
please do a right click on the blue bzinst_ bar at the bottom. There you should have the option to click on "Move" or "Restore". Maybe try a few things there if the Backblaze installer comes up.
I will check if there is a way to force a "full screen" for the installer when launched, but I am not sure when I have time for that.
Please let me know if you see the installer window after that.
Thank you!

**Comment by psiberfunk** [comment]
> please do a right click on the blue bzinst_ bar at the bottom. There you should have the option to click on "Move" or "Restore". Maybe try a few things there if the Backblaze installer comes up. I will check if there is a way to force a "full screen" for the installer when launched, but I am not sure when I have time for that. Please let me know if you see the installer window after that. Thank you!
> 
> Edit: What I see from the logs, everything works as it should. After Backblaze is installed you should see all drives and with UID/GID=0 all files should be accessible by Backblaze.

So, sadly that didn't work right.. eventually I killed the task, and re-ran it a few times after a restart of the container from explorer.exe within the VNC and got it to appear.. but it was very janky/unreliable.  I'm not sure exactly which combination of muddling about fixed it sadly..

**Comment by traktuner** [comment]
Thank you!
I'll look into that, but I'm not sure if that is an issue with the Backblaze installer or the Wine virtual desktop implementation.

**Comment by psiberfunk** [comment]
It could have been that other change I suggested to fix the white box, lolOn Feb 19, 2024, at 11:45 PM, Thomas ***@***.***> wrote:﻿
Thank you!
I'll look into that, but I'm not sure if that is an issue with the Backblaze installer or the Wine virtual desktop implementation.
