### ISSUE TITLE
Could not communicate with backblaze, install failed 

### ISSUE THREAD

**Issue by skylatian** [JonathanTreffler/backblaze-personal-wine-container#13]
You'd think it was a networking issue (maybe it still is!) but the container is able to successfully download and install the required dependencies, and I'm able to access https://ca000.backblaze.com on the same network (though it just routes to their homepage, plus a long string after the URL). Any idea what could be causing this?

![image](https://user-images.githubusercontent.com/53362705/162109890-1f3bc6d1-2107-45bd-83dd-26e6e6fc0ea5.png)

**Comment by JonathanTreffler** [comment]
Duplicate of #4

There is a section about this in the [Troubleshooting](https://github.com/JonathanTreffler/backblaze-personal-wine-container#troubleshooting) section of the README.

**Comment by skylatian** [comment]
apologies! that worked great, I missed that section in troubleshooting. Thanks!
