### ISSUE TITLE
New Installs Failing

### ISSUE THREAD

**Issue by newoski** [JonathanTreffler/backblaze-personal-wine-container#131]
I'm suddenly getting errors whenever I try to install the docker now on Unraid. No changes to the parameters that were working yesterday

Installer just fails:
https://pastebin.com/5DYhuyGb

**Comment by traktuner** [comment]
Hey,
please try the versioned tag v1.7.1
Seems like the unattended install is not working on every setup. Will look into that issue.

**Comment by newoski** [comment]
That worked, thank you!

**Comment by nathaningram** [comment]
I'm having this same issue. How do I install 1.7.1? I've downloaded the zip for the 1.7.1 tag here, but the docs I've found say it has to be a .tar. This is probably a simple answer, but I'm new at this. Any insight appreciated. Thanks!
