### ISSUE TITLE
Unable to add backup drive due to permission issues

### ISSUE THREAD

**Issue by ADeadPixel** [JonathanTreffler/backblaze-personal-wine-container#138]
Running in unRaid 6.12.8 in a docker container. Here is my docker run command
```docker
docker run
  -d
  --name='Backblaze_Personal_Backup'
  --net='bridge'
  --privileged=true
  -e TZ="America/Chicago"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Testing"
  -e HOST_CONTAINERNAME="Backblaze_Personal_Backup"
  -e 'SECURE_CONNECTION'='0'
  -e 'TZ'='CST'
  -e 'DISPLAY_WIDTH'='900'
  -e 'DISPLAY_HEIGHT'='700'
  -e 'VNC_PASSWORD'=''
  -e 'FORCE_LATEST_UPDATE'='true'
  -e '{1}'='0'
  -e 'GROUP_ID'='0'
  -e 'CLEAN_TMP_DIR'='1'
  -e 'DISABLE_AUTOUPDATE'='false'
  -e 'X11VNC_EXTRA_OPTS'=''
  -e 'ENABLE_CJK_FONT'=''
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:5800]/'
  -l net.unraid.docker.icon='https://www.backblaze.com/pics/cloud-blaze.png'
  -p '5800:5800/tcp'
  -p '5900:5900/tcp'
  -v '/mnt/user/Photos/':'/backup_volume/':'rw'
  -v '/mnt/user/appdata/Backblaze_Personal_Backup':'/config':'rw'
  --init 'tessypowder/backblaze-personal-wine:ubuntu22'

f875406ea4593b651f28711204006f16a2f13bd72123a30d0ecf95582f96e712

The command finished successfully!
```
First permission warning:
![image](https://github.com/JonathanTreffler/backblaze-personal-wine-container/assets/53877960/606f38de-fe00-4fde-ab86-09c9555f652e)
I found in some other issues that this warning is benign and can be ignored. 

For some reason I do not see a D: drive but instead I see a Z: drive. Going into the drive I can see the files I want to backup/exclude. 
![image](https://github.com/JonathanTreffler/backblaze-personal-wine-container/assets/53877960/abd36264-4790-475b-b566-98a811c8a50e)

But when I select the Z: drive I get the following error:
![image](https://github.com/JonathanTreffler/backblaze-personal-wine-container/assets/53877960/97c602de-4af6-4570-8107-fea6948bb650)

I updated the docker image to use `:ubuntu22` as some of the threads suggested, set my docker container to run as elevated, and set the USER_ID and GROUP_ID to 0 as suggested in the troubleshooting section. Sadly, nothing has worked so far.

**Comment by traktuner** [comment]
Hey!
Are your mounts local mounts on the same machine or is "/mnt/user/Photos/" on a separate machine in your network?
Because that would be not supported currently - I guess this is a limitation by WINE.

**Comment by traktuner** [comment]
> USER_ID and GROUP_ID to 0

Also I noticed that you set `-e 'GROUP_ID'='0'` but I can't see `-e 'USER_ID'='0'`
Please check if that's just a copy paste error here or if it's missing in your docker run command.

**Comment by Bovive** [comment]
I also had quite a time getting this to work with Unraid, however I was able to do so. I think in some part it comes down to the Unraid template being a bit misleading or at the very least lacking in instructions. I read a lot of different posts and here are my notes for getting it to work:

Change USER_ID to 0.
Change GROUP_ID to 0.
Run Privileged.
Change the docker template container path from "/backup_volume/" to "/drive_d/".
Do **NOT** Run in container this line as we already identified the drive: ln -s /drive_d/ /config/wine/dosdevices/d:
If the window doesn't show during Backblaze install: Right click and click "Move".
If stuck on detecting drive at end. Restart container after some time.
To see if it is actually still being scanned you can type "lsof -r 1 -w /mnt/user | grep drive_d" in the Unraid terminal.
Now can see drive D: and it rescans after it is selected.
Unselect Z: from backup.

The permission issue warning is a popup that you can ignore. Many Unraid users said the same thing on the Unraid forums. The biggest thing for me was to change "/backup_volume/" to "/drive_d/" on the Unraid template.

**Comment by traktuner** [comment]
Thank you very much for the investigation :)
Please note that it’s no longer necessary to manually create the symlinks
`ln -s /drive_d/ /config/wine/dosdevices/d:`
If you mount the drives you’d like to backup correctly with drive_d drive_e etc. those will automatically mount since our release v1.7

We investigated the permission popup quite a bit but if the container can download and install the Backblaze app, the permissions are sufficient so this warning can be ignored.

please feel free to create a Q&A post in the discussion section with your troubleshooting tips to help others with the same issues.

thank you!
