### ISSUE TITLE
problem is that the password field

### ISSUE THREAD

**Issue by alessandro1501** [JonathanTreffler/backblaze-personal-wine-container#141]
Hi, my problem is that the password field doesn't appear,
![Screenshot 2024-03-31 114554](https://github.com/JonathanTreffler/backblaze-personal-wine-container/assets/34516704/5fe31ec1-4d28-4af1-a439-c2d237926ac6)
 is it possible to unblock the situation?
 is there a procedure?
[backblaze-wine-startapp.log](https://github.com/JonathanTreffler/backblaze-personal-wine-container/files/14814951/backblaze-wine-startapp.log)

**Comment by traktuner** [comment]
Hey @alessandro1501 
unfortunately I could not reproduce the issue.
what happens when you insert youe mail and hit <enter> on your keyboard?
Are you using the latest version v1.8.1 of our container?
If this is the case, could you please change the docker tag to :ubuntu22 and see if this changes anything?

**Comment by twist3dimages** [comment]
This happens to me too, it wants to use google oauth

**Comment by thefirstmojo** [comment]
this error is happening when you log in with your google login and not with email and Password. switch your login options and it will work

**Comment by twist3dimages** [comment]
> this error is happening when you log in with your google login and not with email and Password. switch your login options and it will work

that worked for me

**Comment by traktuner** [comment]
As @thefirstmojo said, only the native Backblaze login is supported by our container.
Please create a new Backblaze account (without Google sign-in) and try again to login.
