### ISSUE TITLE
Encryption Key, can't paste in the Wine GUI

### ISSUE THREAD

**Issue by sbcrumb** [JonathanTreffler/backblaze-personal-wine-container#149]
I really want to add an encryption key. However what I want to use is well long and I don't want to type it.. How can I paste into the GUI? Or another way to get that data applied?

**Comment by JonathanTreffler** [comment]
look at the left side of your screen :)

(There is a menu for controlling the clipboard)

**Comment by sbcrumb** [comment]
Dang I feel dumb.. I missed that. Thank you.
