### ISSUE TITLE
installer not loading

### ISSUE THREAD

**Issue by 14paavang** [JonathanTreffler/backblaze-personal-wine-container#160]
<img width="959" alt="Screenshot 2024-05-31 183735" src="https://github.com/JonathanTreffler/backblaze-personal-wine-container/assets/81815334/e07c4336-e89d-4184-b9ad-c01c43d8011c">
<img width="959" alt="Screenshot 2024-05-31 183735" src="https://github.com/JonathanTreffler/backblaze-personal-wine-container/assets/81815334/e07c4336-e89d-4184-b9ad-c01c43d8011c">
<img width="959" alt="Screenshot 2024-05-31 183735" src="https://github.com/JonathanTreffler/backblaze-personal-wine-container/assets/81815334/e07c4336-e89d-4184-b9ad-c01c43d8011c">

When i configure it exactly as the example given in the readme, other than the different port, it works, but for some reason, it seems to get stuck at this page and does not load up the installer, i have tried this multiple times and ended up with the same result. B4 it did boot into the installer and then allowed me to enter my Email, but then the password field was not there ( I was trying to recreate the issue when it stopped loading the installer)

**Comment by 14paavang** [comment]
<img width="381" alt="Screenshot 2024-05-31 184802" src="https://github.com/JonathanTreffler/backblaze-personal-wine-container/assets/81815334/677064e8-1c57-4d0d-abbf-f6806aea4b37">
<img width="265" alt="Screenshot 2024-05-31 184740" src="https://github.com/JonathanTreffler/backblaze-personal-wine-container/assets/81815334/8f778910-92cc-4e0c-97b9-a93f05ae421d">
<img width="274" alt="Screenshot 2024-05-31 184722" src="https://github.com/JonathanTreffler/backblaze-personal-wine-container/assets/81815334/974f837a-efd9-48c2-ad22-489f80ea0667">
<img width="485" alt="Screenshot 2024-05-31 184657" src="https://github.com/JonathanTreffler/backblaze-personal-wine-container/assets/81815334/2e459e96-5ecf-49e5-a623-cbe633bcd75c">
<img width="386" alt="Screenshot 2024-05-31 184633" src="https://github.com/JonathanTreffler/backblaze-personal-wine-container/assets/81815334/086f0519-05b2-4edf-9ddc-b7ee240a65f7">
these are all the exact settings

**Comment by AdrianDeWinter** [comment]
For anyone else running into this problem in the future,
I just had the same thing and it turned out that just waiting a while (~5 mins) solved things
