### ISSUE TITLE
Computer Not Backed Up For 15 Days (Update Needed?)

### ISSUE THREAD

**Issue by axemanozh** [JonathanTreffler/backblaze-personal-wine-container#162]
Hello,

I received the automated e-mail from Backblaze today that my docker instance has not been backed up for 15 days. I checked to verify it was running normally and seems to be.

<img width="738" alt="backblaze1" src="https://github.com/JonathanTreffler/backblaze-personal-wine-container/assets/59229270/9d133e3a-103a-48e8-89a6-a9c33a3cd825">

Backblaze recommends running the latest version as the first step to remedy the issue, and when I click Check For Updates, a new version does seem to be available (9.0.1.777). Clicking the Download button does not seem to do anything (I presume this is blocked by the functionality of the docker).

<img width="261" alt="backblaze2" src="https://github.com/JonathanTreffler/backblaze-personal-wine-container/assets/59229270/e168a865-a22c-43f8-9040-24b145e1c549">

In the past before the auto-update functionality was added to the docker, I was able to force updates by going into the config directory and removing bzbui.exe from the drive_c -> Program Files (x86) -> Backblaze directory, which would cause the docker to download and run the latest installer directly from Backblaze, as far as I could tell. I tried to do that now, but it downloaded version 767 again, which I presume is the latest "approved" version for the docker in the auto-update functionality added by traktuner. Is there a way I can get 777 installed or resolve the "Computer Not Backed Up" issue before Backblaze removes my backup?

**Comment by traktuner** [comment]
Hey,
according to the Backblaze app there is nothing new to back up. Please check all folder permissions, and if you can also list all files/folders from inside the docker container.
Also, please post all docker logs and the startapp.log here, so we can troubleshoot further.

Please note, that the version 9.0.1.777 is currently the latest available version.

**Comment by traktuner** [comment]
As long as you did not set "DISABLE_AUTOUPDATE=true" in the environment variables, the container will auto-update itself, and by declaring "FORCE_LATEST_UPDATE=true" it will update to the latest version which is available officially from Backblaze. And as I can see you are already on the latest version, so there is no newer Backblaze version you can update to.

Where do you see the "Computer not connected" message? I can't see it in your screenshot.
Normally you only see that message when there is either a Backblaze outage or an internet connectivity issue with your docker container. But I don't think that this is the case.

You can also login to back blaze.com and verify in the list with your volumes when it was last backed up. Maybe that message got sent by mistake.

**Comment by axemanozh** [comment]
I'm away from home right now, but when I view the file version in the container directory it says it's version 767 and clicking Check for Update in the corner says there is the 767 version available to download, so I guess I'm confused lol

**Comment by axemanozh** [comment]
And, of course, now that I opened this issue ticket, I get the Backblaze backup summary this morning saying that everything is up-to-date. I'm still not clear if my docker has the updated version (777) however, I'll send what I'm seeing when I get home later today.

**Comment by axemanozh** [comment]
> Great! According to your own screenshot <img alt="backblaze2" width="261" src="https://private-user-images.githubusercontent.com/59229270/335825725-e168a865-a22c-43f8-9040-24b145e1c549.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1MTAyMDYsIm5iZiI6MTcxNzUwOTkwNiwicGF0aCI6Ii81OTIyOTI3MC8zMzU4MjU3MjUtZTE2OGE4NjUtYTIyYy00M2Y4LTkwNDAtMjRiMTQ1ZTFjNTQ5LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDE0MDUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0NTUwMDU4YTViMmRlODIwNjRjNDlhYjMzNjVlOGQyMGQyNTE0NjM0ZTcyOTk0ZTMwY2I4YTRiMmJiMmQzNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pyDauC7DBDvZifilzRNqNml81v2IBkFmVU24zda11SY"> you are on 777

Sorry to be obtuse, but that's what I get when I click "Check For Updates" in the bottom right corner, telling me that an update is available? Nothing happens when I click the Download button. If I right click the backblaze executable in the container file directory, and check the version number, it is 767.

**Comment by traktuner** [comment]
Haha, very sorry, yo hare right. The about screen is what I meant and the update available screen looks very similar.
767 is our latest known-good version. 
777 ist the latest available version directly from Backblaze.
By default the container downloads our known-good version. 
Since 777 is out for some time now and I didn't have any problems with it yet I will push an update to the container soon. When you then update your container, the Backblaze app will auto update itself.

**Comment by axemanozh** [comment]
Awesome, thanks. Looks like my issue is most likely fixed, not sure if it was because it was a glitch from Backblaze or because I didn't upload or make any file changes to my repository for a while and the client detects that as offline (seems like it should still know that the machine is online even if files haven't been modified, but who knows how Backblaze has their logic designed.)

**Comment by axemanozh** [comment]
Just as an update, I've confirmed Backblaze is indeed seeing my container as online and fully backed up. Still not sure exactly what the root cause was, but thanks @traktuner and @JonathanTreffler for your great container here, it's so useful. Looking forward to the update for the new version!
