### ISSUE TITLE
Error something went badly wrong, first installation 

### ISSUE THREAD

**Issue by GasPoweredTomato** [JonathanTreffler/backblaze-personal-wine-container#164]
![image](https://github.com/JonathanTreffler/backblaze-personal-wine-container/assets/64394824/10bdcd84-45ab-4936-8954-7b5ec8931eb0)
Just installed this on unraid. Kept all the settings default since they looked good. On initial start up, after putting in my credentials, this is the error I am getting

**Comment by Gon-97** [comment]
Same thing happens to me. Also did a default install on unraid.

**Comment by traktuner** [comment]
Hey,
this seems to be an issue on the Backblaze server side since I have seen that error before and it went away after some time:
https://www.reddit.com/r/backblaze/comments/188cv14/installation_error_something_went_badly_wrong/

**Comment by GasPoweredTomato** [comment]
This appears to have resolved itself. It is now working.
