### ISSUE TITLE
New install not working

### ISSUE THREAD

**Issue by thehatch2002** [JonathanTreffler/backblaze-personal-wine-container#17]
I went to try this docker..After first install it does not load the /mnt/user folder as a drive.  After some time I discovered I had to run winecfg through the docker console and manually add it and restart the docker.  I had it working..and then eventually it came up as a disconnected drive and then I just had to reinstall this.

**Comment by JonathanTreffler** [comment]
Please install it using the installation steps in the README, it is tricky to do it on your own.

**Comment by JonathanTreffler** [comment]
Closing this issue, because it is stale, feel free to ask me to re-open it, if the issue still exists.
