### ISSUE TITLE
New Docker create doesn't Seem to start and install

### ISSUE THREAD

**Issue by sbcrumb** [JonathanTreffler/backblaze-personal-wine-container#173]
`docker run     -p 8080:5800     --init     --name backblaze_personal_backup     -e FORCE_LATEST_UPDATE=true     -e DISABLE_AUTOUPDATE=false     -e WINEARCH=win32     -e WINEPREFIX=/config/wine32     -v "/srv/mergerfs/backblaze/:/drive_d/"     -v "/srv/mergerfs/Data/Docker-Data/backblaze/:/config/"     tessypowder/backblaze-personal-wine:latest`

Sorry having an issue formating it.
https://pastebin.com/mELZrVGE

**Comment by traktuner** [comment]
Hey @sbcrumb 
the environment variables
`WINEARCH`
and
`WINEPREFIX`
are not supported. Those are set by us, and if you overwrite them by environment variables, the installation won't work.
Please stop the container, completely remove the contents of your config folder and start the container again without the variables above.

**Comment by sbcrumb** [comment]
Ok thanks I did try that today here is my docker command and the output

`docker run \
    -p 8080:5800 \
    --init \
    --name backblaze_personal_backup \
    -v "/srv/mergerfs/backblaze/:/drive_d/" \
    -v "/opt/blaze/:/config/" \
    tessypowder/backblaze-personal-wine:latest`


https://pastebin.com/h9Z8sfcW

**Comment by traktuner** [comment]
Hey,
thank you for the logs! I create a PR to fix this issue.
