### ISSUE TITLE
Unraid exclusive shares not visible to Backblaze

### ISSUE THREAD

**Issue by Austinzveare** [JonathanTreffler/backblaze-personal-wine-container#175]
I have the User folder passed through as Drive D, some of my shares aren't exclusive, but those that are aren't being backed up by Backblaze because their not visible. What can I do to be to be able to have all my shares backed up?

**Comment by JonathanTreffler** [comment]
It is not reccommended to pass through your entire user folder, it is better to add a drive for every share you want to back up.

**Comment by Austinzveare** [comment]
> It is not reccommended to pass through your entire user folder, it is better to add a drive for every share you want to back up.

Got it, that makes sense. Would I just add several other path variables to the config as "drive_e", "drive_f", etc. ? And would this mean I would effectively have to reupload everything since these are additional "drives"?

**Comment by JonathanTreffler** [comment]
> Would I just add several other path variables to the config as "drive_e", "drive_f", etc. ?

Yes



> And would this mean I would effectively have to reupload everything since these are additional "drives"?

No, backblaze will recognize, that file files are the same, but it will have to begin the scan from the beginning, which will take time depending on the number of files.
