### ISSUE TITLE
updated and became broken.

### ISSUE THREAD

**Issue by thehatch2002** [JonathanTreffler/backblaze-personal-wine-container#177]
I run unraid.  

After installing the latest update via docker just left with a empty wine screen.   After attempting to resolve this and downloading a new blaze insallter with curl and running the app manually through the console...the install never pops up.  I have a backup of the entire folder of the wine on another server.  So, I downloaded it reloaded it.  I set the force update from true to false..  Now It says my installation is incorrect, and I tried using an updated exe I had used before the docker update which now just hangs with wine background just chillin and nothing coming up.

   Anyone have a suggestion for me?  This is how I ran my update file..  I added a bash to user app, su into app and moved into the folder with my backblaze update exe file and ran wine64 backblaze_installer.exe  is it not loading up onto the new screen that I am viewing or what?  Winecfg and wine explorer pops right up on my screen..so I am baffled here.

**Comment by thehatch2002** [comment]
Looks like I figured it out. I had to add :ubuntu22 at the end of my image.  <.< oof.  I spent some hours on this one.

**Comment by traktuner** [comment]
Hey,
that's odd. All tags (main, latest, versioned) are actually the ubuntu22 image.
I guess that's related to the virtual desktop mode, and the installer only appears in the background.
It should be fixed with #168 wehre the virtual desktop mode is opt-in.
