### ISSUE TITLE
BackBlaze app showing 208 TB of data

### ISSUE THREAD

**Issue by SC8198** [JonathanTreffler/backblaze-personal-wine-container#179]
Hi,

I got the container to work however it is showing a lot more data to backup than I have. Currently have around 76.7 TB of stuff and the app shows over 208 TB. Any ideas on what might cause this??

I am on the latest build on unraid

**Comment by traktuner** [comment]
Hey,
Do you probably have a system which can do volume snapshots and maybe the container sees those?
Can you maybe add more details on your stetup?

**Comment by SC8198** [comment]
Yea,

Running 6.12.8
Running Latest Image
D: drive in Wine is mapped to /backup_volume/ which is mapped to /mnt/user/ on unraid.

Backblaze is set to backup D: and C:

Anything else you wanna know I can get,
Thanks

**Comment by traktuner** [comment]
Thanks!
Do you use the snapshot functionality in unraid?
Can you try to ssh into your container and check the size of the backup volume with
`du -sh /backup_volume`

Also please note that Backblaze Personal is in no way made for such large amounts of data. The backup will probably be *very* slow, please keep that in mind.

**Comment by SC8198** [comment]
I do understand about the size, I was just doing testing to set it up, most likely going to only pass through important data and not my whole server.
I do not use the snapshot functionality. I do have a cache drive that is ZFS what does, however that path isn't in /mnt/user/

![image](https://github.com/JonathanTreffler/backblaze-personal-wine-container/assets/104422567/e92c8375-f682-4c81-a3e5-62fe25785ca3)

Seems that the container sees it right.

**Comment by traktuner** [comment]
> I do understand about the size, I was just doing testing to set it up, most likely going to only pass through important data and not my whole server. I do not use the snapshot functionality. I do have a cache drive that is ZFS what does, however that path isn't in /mnt/user/
> 
> ![image](https://private-user-images.githubusercontent.com/104422567/346413582-e92c8375-f682-4c81-a3e5-62fe25785ca3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NjQ1MjksIm5iZiI6MTcyMDc2NDIyOSwicGF0aCI6Ii8xMDQ0MjI1NjcvMzQ2NDEzNTgyLWU5MmM4Mzc1LWY2ODItNGM4MS1hM2U1LTYyZmUyNTc4NWNhMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMlQwNjAzNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOTE3MTMwMTNkZDMxNzZhYzM0ZjM3ODcyNjg0ZWE5OGUzMjNhYzIyNWU0ODYzYWI2MjBmN2EyODgxZjE2NjFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GLIzHU2VX4FO9nk5Om03ijtkapKZpnnq_tkTRz7UtcA)
> 
> Seems that the container sees it right.

Hey,
I would suggest to let the backup running in continuous mode for some days, without any interruption (no restart of the container, etc) and then check the issues tab in the Backblaze app. If you see 68TB from inside the container then the app itself should also see that exact amount.
Maybe something is wrong with your drive_c (config folder) which has more in it than the Backblaze installation itself?

**Comment by SC8198** [comment]
Okay I will run it for some more time, I don't believe the C drive is mapped to anything that big.

**Comment by traktuner** [comment]
Hey,

Let's check the Backblaze logs to see if we can find anything. They are located in the following directory:

<your config folder>/wine/drive_c/ProgramData/Backblaze/bzdata/bzfilelists/

There is a file called 
`bigfilelist.dat`
Please open it with a text editor. The files and folders are listed from largest to smallest. You should be able to see what accounts for the 137TB there.

**Comment by SC8198** [comment]
Sweet thank ya! Ill take a look in a few!

**Comment by SC8198** [comment]
Okay I think I found the bad file. It was I believe a Rsync backup that I had ages ago set up and a file in the dir was like 130 TB.

It was the Core file if anyone knows what that is that would be cool.

Also if anyone ever needs the path @traktuner posted, on unraid it's 

/config/wine/drive_c/ProgramData/Backblaze/bzdata/bzfilelists

Thank you @traktuner for pointing me in the right direction
