### ISSUE TITLE
Increasingly high RAM use

### ISSUE THREAD

**Issue by Beller0ph1** [JonathanTreffler/backblaze-personal-wine-container#18]
I'm running this on an (older) Unraid server.  I can watch my RAM use go up over time, all due to this container.
The RAM use happens faster during a backup, but it even increases while sitting idle under "continuous" backup with no operations happening.  I saw another user reference this issue [(thehatch2002](https://github.com/JonathanTreffler/backblaze-personal-wine-container/issues/6#issuecomment-1201675608)) in the [ERR_NotificationDialog thread](https://github.com/JonathanTreffler/backblaze-personal-wine-container/issues/6).

Restarting the container resets the total RAM used, but it continues to climb over time.

Let me know if I should post any screenshots.

**Comment by JonathanTreffler** [comment]
If you installed it through the unraid community app store this is automatically added, but if you installed it manually: Don't forget to add the "--init" flag to the Extra Parameters.

I also noticed the high RAM usage on my own server and mitigated it by limiting the amount of RAM the container is allowed to allocate, by adding the "-m 2g" (2g = 2 gigabytes) flag to the Extra Parameters. In case this limit can crash the container when it can't allocate more and the OOM killer ends the wrong process (not sure if that can actually happen) i added the "--restart unless-stopped" flag.

If this container really has a memory leak problem, it is likely an upstream issue with wine, so if you can find out more about it, maybe create a bug report with them. For now, I think the limiting RAM allocation workaround does the trick.

**Comment by ForceConstant** [comment]
Yes I have it restart the container once a day, and everything syncs fine.

**Comment by nitmir** [comment]
Hello,

This may be due to https://bugs.winehq.org/show_bug.cgi?id=52322 and it's fixed in wine 8.0.2.

The latest image on dockerhub use wine 8.0.0.

I  had the winedriver.exe process leaking memory. After rebuilding the docker image from Dockerfile, wine is up to date (8.0.2)  and I no longer have the memory leak.

Cheer

**Comment by JonathanTreffler** [comment]
> Hello,
> 
> This may be due to https://bugs.winehq.org/show_bug.cgi?id=52322 and it's fixed in wine 8.0.2.
> 
> The latest image on dockerhub use wine 8.0.0.
> 
> I had the winedriver.exe process leaking memory. After rebuilding the docker image from Dockerfile, wine is up to date (8.0.2) and I no longer have the memory leak.
> 
> Cheer

Thank you for the information. I will trigger a new build of the docker image to get the newest wine version to everybody :)
