### ISSUE TITLE
Slow speed on latest version

### ISSUE THREAD

**Issue by Powablocks** [JonathanTreffler/backblaze-personal-wine-container#186]
Hello,

I have really slow speed on the latest version (9.0.2.789) does anyone else have this problem ?

I've seen there were good version on the way back machine but not anymore.

**Comment by Powablocks** [comment]
I tried running v9.0.0.749 it was really fast and good but then it autoupdate to 9.0.1.767 and I'm back to slow speed. Does anyone know how to disable auto update ? 
In unraid docker I already have Force Latest Update to false and Disable Autoupdate to true.

**Comment by ArcticNerd** [comment]
I just decided to start using this system.. and my currently initial upload will finish in like.. 4 years currently with the speeds. Just wondering if there's anything else I can do? Everyone else seems to have said they had no trouble with speeds until the newest versions of the client.

**Comment by Austinzveare** [comment]
We really need an update on this speed issue, I haven't been able to be anywhere close to backed up for months because of the 6mb upload speed.

**Comment by Powablocks** [comment]
I actually have good speed in 9.0.0.749 but it always auto update. If any one have a solution to this

**Comment by Powablocks** [comment]
I found a solution, not the best but I stopped using this docker and run a windows VM and installed the official app. Now it works really well

**Comment by rursache** [comment]
to prevent autoupdates simply create a empty file named `bzupdate` and `bzupdates` in the `C:\Program Files (x86)\Backblaze` folder. this way it wont be able to download the updates as the files are not directories. simple!

**Comment by Austinzveare** [comment]
Great thanks! What's the best way to downgrade the container to 9.0.0.749?

**Comment by rursache** [comment]
uninstall using `wine explorer` and then find `Backblaze_v9.0.0.749.exe` in the attachment. 

- the password is my username
- remove the `.zip` extension as github won't allow `rar` files

[Backblaze_v9.0.0.749.exe.part1.rar.zip](https://github.com/user-attachments/files/16911134/Backblaze_v9.0.0.749.exe.part1.rar.zip)
[Backblaze_v9.0.0.749.exe.part2.rar.zip](https://github.com/user-attachments/files/16911133/Backblaze_v9.0.0.749.exe.part2.rar.zip)

**Comment by Austinzveare** [comment]
Thanks, I'll try this out when I have a moment.

**Comment by JonathanTreffler** [comment]
> uninstall using `wine explorer` and then find `Backblaze_v9.0.0.749.exe` in the attachment. then run it but before login, create the files. at the end use "inherit backup state" and you should be golden!
> 
>     * the password is my username
> 
>     * remove the `.zip` extension as github won't allow `rar` files
> 
> 
> [Backblaze_v9.0.0.749.exe.part1.rar.zip](https://github.com/user-attachments/files/16911134/Backblaze_v9.0.0.749.exe.part1.rar.zip) [Backblaze_v9.0.0.749.exe.part2.rar.zip](https://github.com/user-attachments/files/16911133/Backblaze_v9.0.0.749.exe.part2.rar.zip)

People, please.

I get the interest to downgrade, but I do not recommend redistributing Backblaze binaries. There are good reasons this docker does not do that and downloads it straight from Backblaze or the Internet Archive. Backblaze is not FOSS Software, that means it does not have a license that allows redistribution. If doing so despite that is a potential legal problem for you depends on your jurisdiction and is not really my problem, I am not your lawyer.

But what is my problem: making sure people don't get infected with malware in the comments of this project. And posting random encrypted filetype extension changed split up files is not conducive to that.

So obviously seeing this I quickly booted up a virtual machine to determine if these files are a potential threat and thankfully found no danger. Phew. (I am not a security researcher, check for yourself, don't blindly trust my judgement).

Here is the Virustotal Report: https://www.virustotal.com/gui/file/aa001e997c4a51ca44efb0488a8d10295e476c6e099203fda8f9d801bc569fb6/details .
It has a valid signature by BACKBLAZE, INC. so it was not modified.

While the Github uploads seem to be stable static links the mirror link files could get changed at any time, so I edited the comment to remove it.

This has not happened before, so we didn't have an established rule that has been broken here, but going forward my stance on this is:
I do not always have or want to take the time to safety check stuff like this so expect binary uploads to get hidden/warning label added/deleted on sight.
I get you only want to help, but bad actors in open source are not new and I am sure Jia Tan seemed like a super helpful person too (context for the uninitiated: https://en.wikipedia.org/wiki/XZ_Utils_backdoor) so it really does not make a difference from a moderation perspective.

Note: I am only talking about moderation actions by me, Github obviously does moderation too and such files are as suspicious as they get, so they might still end up taken down by Github.

**Comment by rursache** [comment]
seems like a big overreation over 
1. a proper fix to prevent automatic updates 
and 
2. providing the actual working version that does not cap file speed.

not such quick actions when these issues arise tho.

i managed to finally upload the remaining 2tb of data yesterday, after wasting a month as abysmal speeds. i wanted to help others to achieve this as well.

while not the most transparent, if [filepuma](https://www.filepuma.com/download/backblaze_9.0.1.777-38987/) (IA and others) can distribute the installer, pretty sure we can too. its not like its some paid drm-locked file.

as always, its more work to help others than just minding your own business

**Comment by JonathanTreffler** [comment]
> not such quick actions when these issues arise tho.

I do not owe you a fast solution in fact I do not owe you a solution at all, this is an open source project. I have university exams soon, so believe ime I have better things to do.

> while not the most transparent, if filepuma (IA and others) can distribute the installer, pretty sure we can too. its not like its some paid drm-locked file.

That is not how any of this works. It's a copyright issue, not a drm issue.

**Comment by rursache** [comment]
The full fixed setup is in my fork: https://github.com/rursache/backblaze-personal-wine-container

@JonathanTreffler 
> believe me I have better things to do.

is too busy to fix things but not busy enough to edit my comments (ban me - oh no!), whine about github and thinking internet archive being sued over books has anything to do with redistributing a 1:1 copy of a freely available software setup kit

FYI, comment history is a thing, you editing does nothing but prevent people from having a functional setup.

🤡

**Comment by traktuner** [comment]
@Powablocks  
I'm sorry, but Backblaze has found a way to detect which platform the app is running on, and it appears they aggressively limit upload speeds when running in Wine. Unfortunately, we can't offer a solution at this time, as Backblaze has also disabled the ability to download older versions of the installer from our trusted source, archive.org. Therefore, we can only download the latest version from the official Backblaze website.

@rursache  
I completely understand your concerns. However, as @JonathanTreffler mentioned, we cannot distribute those binaries ourselves due to copyright restrictions (which is why we can't even display the official Backblaze icon in the web GUI). Unfortunately, our only option is to investigate how they check for the platform and limit upload speeds.
Regarding your request for a quick solution, please take a moment to read this:  
[The Social Contract of Open Source](https://snarky.ca/the-social-contract-of-open-source/)

**Comment by Astroamadeus** [comment]
> Warning
> 
> Moderator actions taken by @JonathanTreffler:
> 
>     * Mirror link deleted (for explanation see [Slow speed on latest version #186 (comment)](https://github.com/JonathanTreffler/backblaze-personal-wine-container/issues/186#issuecomment-2334982466))
> 
>     * Mirror link deleted AGAIN, because comment was edited by OP to hide the moderator warnings. Githubs moderation tools are clearly not good enough to disallow that, so doing that again will result in the comment getting hidden entirely and potentially a ban from the project for wasting maintainer time with childish BS.
> 
> 
> Caution
> 
> Note from Maintainers: We do not recommend downloading/installing Backblaze binaries from anywhere except official sources (Backblaze website) or trusted sources like the Wayback Machine.
> 
> uninstall using `wine explorer` and then find `Backblaze_v9.0.0.749.exe` in the attachment. then run it but before login, create the files. at the end use "inherit backup state" and you should be golden!
> 
> `Backblaze_v9.0.0.749.exe`:
> 
>     1. https://www.filepuma.com/download/backblaze_9.0.0.749-37145//
> 
>     2. [REDACTED]

Unfortunately this does seem to work anymore. As of today (January 2nd, 2025), trying to install Backblaze_v9.0.0.749 or Backblaze_v9.0.1.777 in Wine or Windows gives me this error:

![Capture](https://github.com/user-attachments/assets/54d7f70f-8b20-48fb-8f42-8320a4d89331)

This issue should be reopened.
