### ISSUE TITLE
Backblaze will not backup any additional drives except D:

### ISSUE THREAD

**Issue by MrDecepticon** [JonathanTreffler/backblaze-personal-wine-container#190]
I went through the installation for my Unraid Docker setup and got Backblaze running.  I was able to mount one of my Unraid shares as the D drive and it saw it and finally finished backing it up.  I then went to add more mounts to drive E: and F: using the Docker settings - I just added new paths and pointed them to the appropriate shares.

Restarted Backblaze and while I can see E: and F: if I select them to add to the backup Backblaze goes through the disk check and then nothing.  It acts as if there are no files to backup.  I can use the file browser in wine to view the contents of each mounted drive.  I even checked the permissions using the user "app" and they all look correct according to other issues I've read.

Is creating new Path variables in the Docker setup the appropriate way to add more drives?

**Comment by MrDecepticon** [comment]
Ok, so I think I resolved this on my own?  I changed two things.  1) I made the "Default" path in each of the Path variables in the docker settings mirror the actual path.  And 2) I used the Wineconfig to make sure both the drives were seen as local.  Not sure which one actually worked but I suspect the wineconfig is what did it.  Restarted the backblaze docker and re-selected both the E and F drives and now it is backing it all up.

**Comment by bsheline** [comment]
Can you explain this: "used the Wineconfig to make sure both the drives were seen as local"? I'm having a very similar issue

**Comment by Joly0** [comment]
I am also facing this issue so some enlightenment from @MrDecepticon would be highly appreciated :)

**Comment by MrDecepticon** [comment]
Ok, so I added the drive and BB picked it up without me changing anything.  So I have no clue as to why it initially did not see the files on the drive(s) or why this one picked them up right away.
