### ISSUE TITLE
After restart, most of the UI has disappeared and I can't tell if it's working or not

### ISSUE THREAD

**Issue by coolsaber57** [JonathanTreffler/backblaze-personal-wine-container#25]
Per the title, I restarted the docker container and it now looks like this: 
![image](https://user-images.githubusercontent.com/23609629/191561819-f9053121-795f-4545-b063-742941f3b250.png)

Is there something I need to restart/change?

**Comment by codygp** [comment]
Same, was opening an in depth ticket over the last 24 hours, and just posted. But #26 can be merged with this one since it was first.

**Comment by coolsaber57** [comment]
I'm running this on Unraid.  It was working fine and backed up most of my files, but it did appear to get stuck on a pictures file, which was an old thumbnail photo, so i just deleted it and restarted the docker container.  Then I was just left with the above.

**Comment by monteroman** [comment]
See my post [here](https://github.com/JonathanTreffler/backblaze-personal-wine-container/issues/26#issuecomment-1255425695).  I ran into the same issue on upgrading the v8.0 to 8.5 and it's buggy. Some visuals keep locking up the bzbui.exe and you have to keep restarting it.  The background processes continue to operate though.

**Comment by mcrommert** [comment]
> See my post [here](https://github.com/JonathanTreffler/backblaze-personal-wine-container/issues/26#issuecomment-1255425695). I ran into the same issue on upgrading the v8.0 to 8.5 and it's buggy. Some visuals keep locking up the bzbui.exe and you have to keep restarting it. The background processes continue to operate though.
> 
> I'm also running Unraid and the docker for BackBlaze.

When using ps x i don't see windows processes - i'm on unraid

am i missing something?

**Comment by JonathanTreffler** [comment]
seems solved, see #26
