### ISSUE TITLE
Upgrade to 8.5?

### ISSUE THREAD

**Issue by ForceConstant** [JonathanTreffler/backblaze-personal-wine-container#31]
I was wondering if anyone has tried upgrading to 8.5 yet?

https://www.backblaze.com/blog/announcing-backblaze-computer-backup-v8-5/

**Comment by thehatch2002** [comment]
I tried it..I could only run the installer via sudo and soon as I rebooted the docker it only ran the old version on boot up.  I am not sure how to update it

**Comment by thehatch2002** [comment]
So I think I figured it out.  I downloaded the windows version.  You have console into unraid and run 
"docker exec --user app backblaze_personal_backup   (executable)"  It took me awhile to figure it out.

**Comment by lightmaster** [comment]
I keep mine updated by going into the console (either with the docker command or from within a portainer docker), use `ps x | grep bzbui.exe` to get the PID of `bzbui.exe` (the PID is the 3-4 digit number that starts the line. Then use `kill <PID>` to quit out of the menu for backblaze. You can now click the taskbar at the top and then click `Check for Updates`. It will either give you the option to update or tell you its already up-to-date, as well as starting `bzbui.exe` again.

I am currently up-to-date with version `8.5.0.627`

**Comment by mrozj** [comment]
I tried lightmaster's suggestion and it did not work for me. It gave me the option to download the update but it did not appear to make any changes. The regular control panel just popped back up after hitting Download. 

I also tried thehatch2002's instructions as well but that didn't work either.  I received the error:
bash: syntax error near unexpected token `('

**Comment by lightmaster** [comment]
Try this from previous issue (by "wait a moment or 2", mine took like 3 or 4 minutes to show the upgrade window):

> 8.5.0.623 was released and it seems to have fixed the UI freezing issues. I updated mine by running the following commands from the console of the app:
> ```
>cd /config/wine/dosdevices/c\:/
> curl -L "https://www.backblaze.com/win32/install_backblaze.exe" --output "install_backblaze.exe"
> wine64 "install_backblaze.exe"
> ```
> Wait a moment or two for the UI to come up to install/upgrade.
> 

_Originally posted by @monteroman in https://github.com/JonathanTreffler/backblaze-personal-wine-container/issues/26#issuecomment-1279946829

**Comment by mrozj** [comment]
Thanks monteroman. I was able to get this to work. The only thing I needed to do was to change ownership on /config/wine. 

I needed to Inherit the Backup State and the D and Z drives are showing as missing with other D and Z drives showing up but when I try to select them I get the error: Backblaze could not create a read write .bzvol directory on that drive.  Ugh. Going to try to restart it and see if that helps.

**Comment by mrozj** [comment]
I went into the console for the app and moved to the D drive and removed the existing .bzvol folder. I tried the same thing on the Z drive but it doesn't want to work. I don't really need Z backed up so I think I am good to go now. Thanks for your help.
