### ISSUE TITLE
Won't install client

### ISSUE THREAD

**Issue by Pl4ytimes666** [JonathanTreffler/backblaze-personal-wine-container#4]
![image](https://user-images.githubusercontent.com/96458002/151139378-6c493907-96a1-45ac-95f2-b49051c385e8.png)

After i install all Wine Components the client said that he has no network connection. 
What am i doing wrong ?

**Comment by JonathanTreffler** [comment]
Can you check whether the docker has access to the internet by going into the console and pinging google.com for example?

**Comment by JonathanTreffler** [comment]
Were you able to fix the issue?

**Comment by traktuner** [comment]
Same happens with my client.
https://ca000.backblaze.com can be accessed (wget) with no issues from within the container.

**Comment by JonathanTreffler** [comment]
Do you do anything fancy network-wise? Container network routed through a VPN? Syste wide network proxy? Router with special Firewall Rules?
And which OS are you using ? Unraid ?

**Comment by JonathanTreffler** [comment]
Have you tried removing the container and all the mounted configuration folders and starting the installer again?

**Comment by traktuner** [comment]
Hi,
I am using a Synology NAS as the docker host. No VPN. I also tried the container from @Atemu which does not display this error and goes straight to the login screen. So I assume it has something to do with the ubuntu base image.
Removing the contents of the config folder and starting the installer again -> same issue. It installs mono and then displays the "could not communicate" error.

**Comment by traktuner** [comment]
Update:
It's working for me now. I built the Docker image by myself and used the older 18.04 baseimage. So there has to be a small dependency which is leading to this error. Also debian-10 is working, debian-11 -> same error.
Changes in my forked repo: https://github.com/traktuner/backblaze-personal-wine-container

**Comment by JonathanTreffler** [comment]
Ok, if we cannot figure out what is causing the issue with the newer base image i could merge your fork into a second branch, publish it under a second tag and add an entry to the troubleshooting section in the readme.
Thanks for your debugging :)

**Comment by traktuner** [comment]
You're welcome! Feel free to merge, would be cool if it also helps @Pl4ytimes666 to get it working :)

**Comment by cliss** [comment]
I'm having the exact same problem as @Pl4ytimes666. I'm also hosting on a [very old] Synology NAS.

I attempted to run/build @traktuner's `Dockerfile` by hand, but I couldn't get it to work properly. (This is surely user error.)

Would love to see these fixes merged, if at all possible, please, @JonathanTreffler!

**Comment by JonathanTreffler** [comment]
Ok, i will merge it today or tommorow and release It under a separate tag :)

**Comment by cliss** [comment]
Thanks so much, @JonathanTreffler 🥰

**Comment by JonathanTreffler** [comment]
Sorry it took a few more days, i will merge and publish it now :)

**Comment by JonathanTreffler** [comment]
The ubuntu18 tag is currently being built by the Github Action.
@cliss Would be great if you could test if it fixes your problems once it is done :)

**Comment by cliss** [comment]
Still didn't work for me, but I wonder if this is user error.

Unless I'm unaware, this container isn't published in any sort of registry, right? So I'm trying to roll this all by hand, which is new to me. Regardless, when I run, I get the following.

I haven't seen this before.

```
s6-applyuidgid: fatal: unable to exec /startapp.sh: Exec format error
[services.d] stopping services
[services.d] stopping app...
[services.d] stopping statusmonitor...
[services.d] stopping certsmonitor...
[services.d] stopping nginx...
[services.d] stopping logmonitor...
[services.d] stopping openbox...
[services.d] stopping x11vnc...
caught signal: 15
21/03/2022 13:19:40 deleted 40 tile_row polling images.
[services.d] stopping xvfb...
[services.d] stopping s6-fdholderd...
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
```

**Comment by cliss** [comment]
Update: I think this was, indeed, user error. By [forking](https://github.com/cliss/backblaze-personal-wine-container), and then [branching](https://github.com/cliss/backblaze-personal-wine-container/tree/synology), I **was** able to get everything installed via the command line.

Once I did, I saw this for the very first time!!! :tada: :tada: :beers:
<img width="1427" alt="Screen Shot 2022-03-21 at 9 53 58 AM" src="https://user-images.githubusercontent.com/282460/159275758-f283f3ba-853b-44af-b6a9-74f1b8041dcf.png">

So, I do think it may be worth exploring a different way to release the Ubuntu 18 version. However, things seem to be working now!

Many thanks to both @JonathanTreffler and @traktuner for your help!

**Comment by JonathanTreffler** [comment]
> Unless I'm unaware, this container isn't published in any sort of registry, right? So I'm trying to roll this all by hand, which is new to me. Regardless, when I run, I get the following.

What do you mean by registry ? It is published in the Docker Hub Registry.

**Comment by cliss** [comment]
I'm surely just announcing my own ignorance to the world, but I don't see *this repo* as an option on Docker Hub:

https://hub.docker.com/search?q=backblaze-personal-wine&type=image

**Comment by cliss** [comment]
Oh holy hell I now see that this is a thing. 🤦 

https://hub.docker.com/layers/tessypowder/backblaze-personal-wine/ubuntu18/images/sha256-b50dcce148ec09184175c08792bfb6cac38c77af02484d1cc4bb2cd8632ce985?context=explore

I am, indeed, a dummy.

I somehow told myself that this was a fork of `tessypowder`'s original work. I didn't realize these were one and the same.

My apologies!

**Comment by JonathanTreffler** [comment]
Yeah, tessypowder is my old github name and you cannot change usernames on npm :)
There is a link to the dockerhub page in the repository description.
I am closing this for now.
