### ISSUE TITLE
Upgrading the container from wine-7.0.1 to 8.0

### ISSUE THREAD

**Issue by monteroman** [JonathanTreffler/backblaze-personal-wine-container#42]
Jonathan, is there a way to get the Wine package updated to version 8? I am curious to know if updating the package to 8 would fix some of these issues with the GUI freezing. Also, perhaps if there's an update to Xvfb / VNC that might make it a little more visually stable? 

I tried doing an apt-get upgrade, but was unable to update the packages.

Thanks

**Comment by monteroman** [comment]
I ask this because the latest version of Backblaze is freezing up in the GUI again. I can see the processes chugging away behind the scenes, but the GUI is frozen even on a fresh container reboot.

**Comment by traktuner** [comment]
When the Dockerfile is being built, it downloads the most current version of Wine. So in theory, you could use the Docker image with the "main" tag instead of "latest", maybe Wine 8.0 is already integrated there (Docker images with the "main" tag are built automatically every month.

**Comment by monteroman** [comment]
Success!

The GUI seems to be working now. At least for the moment. I will keep an eye on it and report back.

![Screenshot 2023-01-31 at 7 53 45 AM](https://user-images.githubusercontent.com/5451042/215766929-757cdcfe-11e2-48db-bbc0-689c9786fe90.png)

**Comment by monteroman** [comment]
It's been a day and it's running great with running off the "main" release channel. Wine 8 seems to make it more stable visually and much more responsive.
