### ISSUE TITLE
Is backblaze version 8.5.0.659 broken in this wine container?

### ISSUE THREAD

**Issue by nj2359** [JonathanTreffler/backblaze-personal-wine-container#46]
I first attempted to upgrade my existing container as follows.
first I start an interactive bash shell inside my docker container named "backblaze3"
`docker exec -it --user app backblaze3 /bin/bash`
Then I run the following commands to upgrade
`cd /config/wine/dosdevices/c\:/`
`curl -L "https://www.backblaze.com/win32/install_backblaze.exe" --output "install_backblaze.exe"`
`wine64 "install_backblaze.exe"`

The installer comes up and allows you to run it inside the web gui
after it completes, backblaze ui is broken, it looks like this.
![image](https://user-images.githubusercontent.com/25471276/221381019-090eceb3-d37e-404b-b4a8-2440c1b7be87.png)

I also tried building a new docker container from scratch, when it downloads the latest version of backblaze (8.5.0.659), after it installs, backblaze begins an initial backup, then the UI freezes and becomes unresponsive.  Monitoring of log files indicates nothin is happening.  If you restart the container, the UI looks the same as in the screenshot.

Does anyone know valid links to view the backblaze software version history as well as where to download specific versions?  I want to test the next version back, I'm not sure what version that is.

**Comment by nj2359** [comment]
Actually, it seems the software is still processing files.  You have about 10-15 seconds before the UI breaks on a new build and completely freezes.  From that point on, you can't manage the software any longer.
Is anyone successfully running version 8.5.0.659 in this wine container?

**Comment by nj2359** [comment]
I have built a new container and replaced the backblaze installer wither version 8.5.0.627, which is the only other version I had, when I first started using this wine container.  8.5.0.627 still works.  If I build a new container and let it download the latest version 8.5.0.659 during initial setup like normal, it is broken.

**Comment by LovelyCupOfTea** [comment]
How do you do this with Unraid though as the  application is automatically downloaded from the back blaze server, any ideas if this is going to be fixed as pretty much breaks the back blaze functionality. 

this would be the perfect unraid docker if this can be fixed, please investigate

**Comment by rswafford** [comment]
@nj2359 - its not just you; I'm using this container via Unraid's app manager, and the UI is broken usually for me.  I don't know enough about Wine to offer anything in the way of a fix unfortunately.  I agree it does seem to be still updating my files, just the UI is hosed so I can't select anything new to backup (luckily(?) I'm already fully backed up, so its a steady-state system at this point...)  Hoping it resolves itself, or someone who's better with wine can make a container update to fix this thing...

**Comment by martinlevesque** [comment]
having the same issue as well!

**Comment by Goddy87** [comment]
> having the same issue as well!
> 
> i did the following to fix it (not exactly sure what fixed it):
> 
> * cleaned all existing docker objects (docker system prune -a, remove all images, remove all docker drives)
> * changed image to tessypowder/backblaze-personal-wine:main (instead of latest)
> * complete a fresh install seems to have fix it for now

Thanks for that hint, but did anyone have success with it? 
I'm really scared to try it, because my backup is near finish and don't want to cancel it somehow...

Any expirience with a running backup and delete and setting up the container again, will it restart all over?

And already thanks for the information!

**Comment by JonathanTreffler** [comment]
> > having the same issue as well!
> > i did the following to fix it (not exactly sure what fixed it):
> > 
> > * cleaned all existing docker objects (docker system prune -a, remove all images, remove all docker drives)
> > * changed image to tessypowder/backblaze-personal-wine:main (instead of latest)
> > * complete a fresh install seems to have fix it for now
> 
> Thanks for that hint, but did anyone have success with it? I'm really scared to try it, because my backup is near finish and don't want to cancel it somehow...
> 
> Any expirience with a running backup and delete and setting up the container again, will it restart all over?
> 
> And already thanks for the information!

The Backblaze version will not change if you simply change the docker version tag, because after the update it will detect, that Backblaze is already installed and not run the older installer. You can start from scratch with a tag or keep your configuration and backup by manually installing another version, like shown here (replacing the url, with the version you want as desribed [here](https://github.com/JonathanTreffler/backblaze-personal-wine-container/issues/7#issuecomment-1258881573)):

> `cd /config/wine/dosdevices/c\:/`
> `curl -L "https://www.backblaze.com/win32/install_backblaze.exe" --output "install_backblaze.exe"`
> `wine64 "install_backblaze.exe"`

**Comment by draco1544** [comment]
same issue here, i can't install the app

**Comment by draco1544** [comment]
Same issue here

**Comment by draco1544** [comment]
> wine64 "install_backblaze.exe"

when i'm doing that i have the error with the command `wine64 "install_backblaze.exe"`. The error is `Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: File not found.`

**Comment by ewojo** [comment]
> having the same issue as well!
> 
> i did the following to fix it (not exactly sure what fixed it):
> 
>     * cleaned all existing docker objects (docker system prune -a, remove all images, remove all docker drives)
> 
>     * changed image to tessypowder/backblaze-personal-wine:main (instead of latest)
> 
>     * complete a fresh install seems to have fix it for now

This seems to work for me.  Make sure you're on Wine 8 and everything looks normal.

**Comment by draco1544** [comment]
> having the same issue as well!
> 
> i did the following to fix it (not exactly sure what fixed it):
> 
> * cleaned all existing docker objects (docker system prune -a, remove all images, remove all docker drives)
> * changed image to tessypowder/backblaze-personal-wine:main (instead of latest)
> * complete a fresh install seems to have fix it for now

That’s work for me

**Comment by rswafford** [comment]
Seems to have done the trick for me as well - I simply switched to :master
and I'm back up and running.

**Comment by gmaclean1981** [comment]
New user on Unraid - was having the UI Freeze up after initial install.

Switched to the :master tag and it now appears to be running smoothly!  Thanks!

**Comment by JonathanTreffler** [comment]
There is no "master" tag, I think you mean "main".

Could be that dependency updates since the last versioned release have fixed the issue :+1: .

**Comment by gmaclean1981** [comment]
> There is no "master" tag, I think you mean "main".
> 
> Could be that dependency updates since the last versioned release have fixed the issue 👍 .

You are 100% correct :)  I typed it incorrectly.  I was the :main tag.

**Comment by JonathanTreffler** [comment]
I just released an update (v1.4), :latest should now use the same dependency versions as :main.

**Comment by drewbrashler** [comment]
I am using Unraid, and swapped the repository to tessypowder/backblaze-personal-wine:main as suggested and it fixed the frozen issue for me! Thanks so much!

**Comment by hkrob** [comment]
> I am using Unraid, and swapped the repository to tessypowder/backblaze-personal-wine:main as suggested and it fixed the frozen issue for me! Thanks so much!

Me too, Unraid and changed repositories, the UI prompted to re-install a dependency, did that... Looking good now (will update if it breaks again!)
