### ISSUE TITLE
Feature Request: (Auto) Update Functionality

### ISSUE THREAD

**Issue by monteroman** [JonathanTreffler/backblaze-personal-wine-container#5]
Hi there.  Will the container be updated for the 8.0.1.577 version update or is there a process to update the client?

Thanks for making this!!

**Comment by JonathanTreffler** [comment]
I am documenting my findings in this issue:

There is a command to get the current version:
````bash
docker exec --user app backblaze_personal_backup wine /config/wine/drive_c/Program\ Files\ \(x86\)/Backblaze/bztransmit64.exe -version
````

The same executable also has an auto-update option:
(I am not sure if this is supposed to update this specific component of Backblaze or everything Personal Backup includes)
````bash
docker exec --user app backblaze_personal_backup wine /config/wine/drive_c/Program\ Files\ \(x86\)/Backblaze/bztransmit64.exe -downloadautoupdateifappropriate 
````

But I could not get it to work so far. Logs:
````
20220209002311 - starting bztransmit
20220209002311 - bztransmit_processid=908, my_bztransmit_version=8.0.1.571, numMBytesStartMemSize=14, called with args: arg1=-downloadautoupdateifappropriate 
20220209002311 - DownloadAndRunAutoUpdateIfAppropriate - processid=908 grabbed one day lock, starting check for download....
20220209002311 - FallbackHttpsPostSucceededYippee_not_batch for old_fguid=****removed, because I don't know if it is personal information****, fallbackFguidStr=****removed, because I don't know if it is personal information****, fallbackCvt=****removed, because I don't know if it is personal information****
20220209002311 - DownloadAndRunAutoUpdateIfAppropriate - found in clientversion.xml hguid_list=g
20220209002311 - DownloadAndRunAutoUpdateIfAppropriate - my hguid (1) not in hguid_list=g, so SKIPPING auto-update for now.
````

The question is if this path is even the best one. Being able to update automatically update without user input would be great, but it seems like downloadautoupdateifappropriate is for updating the bztransmit component, not all the other executables.
Also as far as I can tell that is not the way a normal installation gets updated.

**Comment by JonathanTreffler** [comment]
I found the following in the official documentation:
https://help.backblaze.com/hc/en-us/articles/217665068-How-do-I-update-Backblaze-

> - Periodically, Backblaze will automatically update all users to the newest version of Backblaze. No action is required from the user.

My Personal Backup Installation using this docker has not done this yet, but maybe this whole update thing is a non-issue.

**Comment by traktuner** [comment]
What I currently do to update the Backblaze client:
connect into the container's bash with the user "app" (via portainer)
```
cd /config/wine/dosdevices/c\:/
curl -L "https://www.backblaze.com/win32/install_backblaze.exe" --output "install_backblaze.exe"
wine64 "install_backblaze.exe"
```
This starts the setup, after clicking "install" everything gets updated and the client (bzbui.exe) starts and continues backup.

**Comment by JonathanTreffler** [comment]
> What I currently do to update the Backblaze client: connect into the container's bash with the user "app" (via portainer)
> 
> ```
> cd /config/wine/dosdevices/c\:/
> curl -L "https://www.backblaze.com/win32/install_backblaze.exe" --output "install_backblaze.exe"
> wine64 "install_backblaze.exe"
> ```
> 
> This starts the setup, after clicking "install" everything gets updated and the client (bzbui.exe) starts and continues backup.
> 
> Automatic updates never happened, at least with my installation.

I just tried that with my installation and it worked as expected. In a future release this could be added to the docker as a script, that could be run with a single command.
I still think that Backblaze can trigger updates remotely and without user interaction, but they only seem to do so for big updates and not small patches.

**Comment by henryyeh** [comment]
I think the easiest way to update is to just pull the latest container, no?

**Comment by JonathanTreffler** [comment]
> I think the easiest way to update is to just pull the latest container, no?

That will not update the Backblaze Application, only the dependencies on the Linux side like wine. The Backblaze version is determined by the first start of the container, where the newest available version is downloaded from Backblaze.
This is because I don't want to redistribute Backblazes executables within the container image.

**Comment by henryyeh** [comment]
> > I think the easiest way to update is to just pull the latest container, no?
> 
> That will not update the Backblaze Application, only the dependencies on the Linux side like wine. The Backblaze version is determined by the first start of the container, where the newest available version is downloaded from Backblaze. This is because I don't want to redistribute Backblazes executables within the container image.

Doesn't it pull the latest Backblaze installer and update to latest on launch though?

**Comment by JonathanTreffler** [comment]
> > > I think the easiest way to update is to just pull the latest container, no?
> > 
> > 
> > That will not update the Backblaze Application, only the dependencies on the Linux side like wine. The Backblaze version is determined by the first start of the container, where the newest available version is downloaded from Backblaze. This is because I don't want to redistribute Backblazes executables within the container image.
> 
> Doesn't it pull the latest Backblaze installer and update to latest on launch though?

Only if the Backblaze Application could not be detected.

**Comment by henryyeh** [comment]
> Only if the Backblaze Application could not be detected.

That makes sense. Thanks for the explanation. And thank you so much for working on this, much appreciated.

**Comment by smccloud** [comment]
Has anyone been able to install the latest beta using this method?  I downloaded the beta from https://www.backblaze.com/status/backup-beta but I get the following when I try to install it
`app@514a7b7e82a5:/config/wine$ wine64 "install_backblaze.exe"
wine: could not open working directory L"unix\\config\\wine\\", starting in the Windows directory.
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: File not found.`
Using ubuntu20 v1.6 from two days ago.  I can't load winecfg either.

**Comment by traktuner** [comment]
Is the non-beta working OK for you?
please post the command you used to download the installer (including log output) and also the full log when starting the docker container.
Thank you!

**Comment by traktuner** [comment]
> Non-beta works, but it has an upload bug where it keeps uploading the same files and over and over and you can't restore those files. To download and run the installer, I used
> `cd /config/wine/dosdevices/c\:/`
> `curl -L "https://f000.backblazeb2.com/file/b2-computer-backup-public/windows/beta/install_backblaze.exe" --output "install_backblaze.exe"`
> `wine64 "install_backblaze.exe"`

Thank you for the additional information!
I tried some things in my testenvironment and figured out, that the old method (mentioned in https://github.com/JonathanTreffler/backblaze-personal-wine-container/issues/5#issuecomment-1123403019 ) does not work anymore.
The reason is that the docker-baseimage we are using got some major updates in the meantime.
Please wait for the beta version to be released officially and set the environment variable `FORCE_LATEST_UPDATE=true` as described here:
https://github.com/JonathanTreffler/backblaze-personal-wine-container#environment-variables
Then the container will always check for the latest available version at start. You will then see the installer and can proceed with the update.
I may add the option to install the latest beta (with and additional environment variable) in the future when I have time.

**Comment by smccloud** [comment]
> > Non-beta works, but it has an upload bug where it keeps uploading the same files and over and over and you can't restore those files. To download and run the installer, I used
> > `cd /config/wine/dosdevices/c\:/`
> > `curl -L "https://f000.backblazeb2.com/file/b2-computer-backup-public/windows/beta/install_backblaze.exe" --output "install_backblaze.exe"`
> > `wine64 "install_backblaze.exe"`
> 
> Thank you for the additional information! I tried some things in my testenvironment and figured out, that the old method (mentioned in [#5 (comment)](https://github.com/JonathanTreffler/backblaze-personal-wine-container/issues/5#issuecomment-1123403019) ) does not work anymore. The reason is that the docker-baseimage we are using got some major updates in the meantime. Please wait for the beta version to be released officially and set the environment variable `FORCE_LATEST_UPDATE=true` as described here: https://github.com/JonathanTreffler/backblaze-personal-wine-container#environment-variables Then the container will always check for the latest available version at start. You will then see the installer and can proceed with the update. I may add the option to install the latest beta (with and additional environment variable) in the future when I have time.

The ability to run winecfg again would be nice though, even though I can see the start button, I can't see the system tray area.  Which means restores will be "difficult" at best.  And the UNRAID template has yet to be updated with the new fields.
