### ISSUE TITLE
Signin UX fix

### ISSUE THREAD

**Issue by psiberfunk** [JonathanTreffler/backblaze-personal-wine-container#52]
Suggested fix:  You can fix the signin UX by enabling the winecfg "emulate virtual desktop" option, as follows.  Suggested making this a default part of the instructions/setup scripts ?

![image](https://user-images.githubusercontent.com/19777571/232847026-7772ac40-4bd8-4a4a-92f3-00ed3d18ec40.png)

![image](https://user-images.githubusercontent.com/19777571/232846779-8944590a-1438-4ee8-8f37-7dd6cbf93a82.png)

**Comment by JonathanTreffler** [comment]
I will try to get it set automatically, without the need for a manual step in the setup process. Thanks for the suggestion.
