### ISSUE TITLE
Reinstall Backblaze Docker - icon is missing (?)

### ISSUE THREAD

**Issue by monteroman** [JonathanTreffler/backblaze-personal-wine-container#64]
@JonathanTreffler, it looks like Backblaze removed the icon your docker image was pointing to. I had to reinstall my docker apps due to a crash and when Backblaze installed, all I got was a big ? for the icon. Would you know of where one could get this icon back?

**Comment by monteroman** [comment]
I should specify that this is for Unraid.

**Comment by JonathanTreffler** [comment]
I removed the icon, because I do not have the copyright to it. I think i was not technically redistributing it, but i wanted to make sure.
