### ISSUE TITLE
[Question] What does the second point in Additional Information mean? (about .bzvol)

### ISSUE THREAD

**Issue by jiatern** [JonathanTreffler/backblaze-personal-wine-container#65]
> Backblaze will create a .bzvol directory in the root of every hard drive it's configured to back up in which it'll store a full copy of files >100M split into 10M parts. Mount accordingly if you want to preserve SSD erase cycles.

I am about to try this container until I read this point. Does this mean that if I have a single 1GB file, it will split to 100 x 10M parts and store them in the .bzvol directory, effectively using TWICE the space on my hard drive? As this doesn't really make sense to me so I want to understand before I use it.

I have like 10TB of files now and easily more than 70% of them are >100MB. I don't want to consume twice the space on my hard disk for the same file. Can anyone explain to me if this is going to happen?

My alternative understanding is that DURING the backup stage, it will split to 10MB parts > upload > delete all the 10MB parts. If this is correct, then I suppose it will not consume any disk space after backup is done?

**Comment by rursache** [comment]
> DURING the backup stage, it will split to 10MB parts > upload > delete all the 10MB parts

> I suppose it will not consume any disk space after backup is done?

yes to both
