### ISSUE TITLE
Support v9 uploader and restore app

### ISSUE THREAD

**Issue by TaakoMagnusen** [JonathanTreffler/backblaze-personal-wine-container#71]
Backblaze is now rolling out the new v9 backup utility and a new restore app. Does this project plan to upgrade to these newer versions?

**Comment by Gijs735** [comment]
The new client can be downloaded here and will be released by the end of this month: `https://www.backblaze.com/status/backup-beta`.

I hope that this version will be supported as well.

**Comment by JonathanTreffler** [comment]
There is probably no special work necessary to make this docker work with 9.0. New installations of the docker will use the new version, as soon it is stable on the Backblaze website. Existing installation can update manually, for instructions see #5 .

**Comment by zeropoint46** [comment]
I just installed v9, actually it's working fine. However the restore app doesn't work. Its missing text and graphics in the gui. just a bunch of empty panels load. I'll keep experimenting but maybe its just missing some libraries or dependencies in wine.

**Comment by zeropoint46** [comment]
got a bit further but the bzrestore app is crashing, not sure what to do next cause I'm not that experienced with this issue. here is a screen shot:
![image](https://github.com/JonathanTreffler/backblaze-personal-wine-container/assets/6351224/1a548ee1-9166-4c4f-aa7c-241c9eb2b934)
![image](https://github.com/JonathanTreffler/backblaze-personal-wine-container/assets/6351224/167425af-b090-42b6-8814-a2ec16204311)

hope it helps.

**Comment by zeropoint46** [comment]
quick update. I have just updated to the latest version of backblaze client, not 100% sure if it's the prod version or still the beta, but the version number is 9.0.0.749. I have tested the restore app and it's now working so far 100%. I did a test restore and got about 65MB/s or some where in the 800mb/s range for the restore. It also seemed to restore the file create time/date correctly even after I deleted the file and I have compared md5sums on the file and they match. I think this is such huge progress and makes backblaze sooooo much more useable. Anyways, thanks again for all the hard work on this project and I'd say this issue could be closed.

**Comment by smccloud** [comment]
> quick update. I have just updated to the latest version of backblaze client, not 100% sure if it's the prod version or still the beta, but the version number is 9.0.0.749. I have tested the restore app and it's now working so far 100%. I did a test restore and got about 65MB/s or some where in the 700mb/s range for the restore. It also seemed to restore the file create time/date correctly even after I deleted the file and I have compared md5sums on the file and they match. I think this is such huge progress and makes backblaze sooooo much more useable. Anyways, thanks again for all the hard work on this project and I'd say this issue could be closed.
> 
> EDIT: Actually I did forget there is one bug still that is more annoyance and cosmetic but would be nice to have it figured out. In the restore app, you cannot access the close button/X in the top right, so you can't exit the application.

Seeing that I can do this is a godsend.  I accidentally wiped out a drive on my UNRAID server today and thankfully had it fully backed up to Backblaze.

**Comment by zeropoint46** [comment]
> 
> Seeing that I can do this is a godsend. I accidentally wiped out a drive on my UNRAID server today and thankfully had it fully backed up to Backblaze.

Agreed, this is a game changer. From I have backblaze as a last resort emergency if all else fails, to now being a the first place I go to restore from off-site .

**Comment by traktuner** [comment]
Hello,
please try the newly built docker image with the main tag. 
We are using an updated baseimage. 
I tested the integrated restore app and successfully restored a few GB of data.
Unfortunately the bzrestore app can't be closed after that because there is no visible UI to do that.
The workaround is to restart the docker container.

**Comment by zeropoint46** [comment]
> Hello, please try the newly built docker image with the main tag. We are using an updated baseimage. I tested the integrated restore app and successfully restored a few GB of data. Unfortunately the bzrestore app can't be closed after that because there is no visible UI to do that. The workaround is to restart the docker container.

I actually fixed this by enabling virtual desktop mode. Its not as clean looking but it works well.
1. exec into your docker container `docker exec -it --user app CONTAINER_NAME bash`
2. source the env file `source /var/tmp/.cont-env-internal`
3. use the gui tool and go to graphics and enable virtual desktop and set the resolution to match what you have configured in your docker env. I think default is 800x600
4. restart docker container
5. profit?

This gives you a desktop with window dressing and you can close the restore app. Its uglier for sure, but it works.

**Comment by traktuner** [comment]
> > Hello, please try the newly built docker image with the main tag. We are using an updated baseimage. I tested the integrated restore app and successfully restored a few GB of data. Unfortunately the bzrestore app can't be closed after that because there is no visible UI to do that. The workaround is to restart the docker container.
> 
> I actually fixed this by enabling virtual desktop mode. Its not as clean looking but it works well.
> 
>     1. exec into your docker container `docker exec -it --user app CONTAINER_NAME bash`
> 
>     2. source the env file `source /var/tmp/.cont-env-internal`
> 
>     3. run winecfg
> 
>     4. use the gui tool and go to graphics and enable virtual desktop and set the resolution to match what you have configured in your docker env. I think default is 800x600
> 
>     5. restart docker container
> 
>     6. profit?
> 
> 
> This gives you a desktop with window dressing and you can close the restore app. Its uglier for sure, but it works.
> 
> edit: missed a step, fixed.

@JonathanTreffler 
Would that be something which we could consider as a default for this container? The wine GUI has some nice benefits. The new restore app, bzdownloader and also backblaze control panel can be started via start menu.
