### ISSUE TITLE
UnRaid server Crash

### ISSUE THREAD

**Issue by LtColDavenport** [JonathanTreffler/backblaze-personal-wine-container#79]
Hi,
since when I am using this extension I find my server bricked from time to time, needed a restart.

At first, I thought as an hardware problem, but I already tried changing the CPU and it still freezes. RAM it is fine (did a MemTest) and there is no GPU inside. PSU and HDD I really doubt can cause a complete freeze of the system. Maybe the Motherboard, can't really test that.

But even if there is an HW issue, let's say the MOBO, the server crash only when this Docker it is running, sometimes after only 1h and other times after 2 days. But when this extension it is disable, it seems to not crash, or at least not in the same time windows.

I have now tried to limit the number of Threads used by Backblaze in guy (from Automatic --> Manual and set 4), let's see if this change anything.

Any help it is welcome.

**Comment by LtColDavenport** [comment]
Well, by the time of writing this, it is crashed again, even with reduced core...

It is crashed in minutes, while it was up for 24h with the docker disable. So I think this has definitively something to do.

**Comment by Potajito** [comment]
I'm having a similar experience, but running on debian. The container seems to be able to crash the whole server, sometimes it last days, sometimes hours. I tried scheduling restarts but it doesn't seem to help, it keeps crashing (I'd say it makes it worse?). 
I really don't know how to troubleshoot this, any idea?

**Comment by LtColDavenport** [comment]
Hey, the basic issue it seems to be with suspending SATA ports.

I found the server also crashes without Backblaze, even if much less and the issue was solved with configuring powertop to default values.

Hope this helped.

**Comment by Potajito** [comment]
Yeah, this ended up not being directly related to this (wonderful) project. In my case it was a faulty old ssd, and the strain of this container just triggered its issues more often.
