### ISSUE TITLE
Unable to create .bzvol on Z drive. D Drive missing from app

### ISSUE THREAD

**Issue by cpsmith516** [JonathanTreffler/backblaze-personal-wine-container#80]
As the title says.

Running container on Unraid, and once inside the app I only see C and Z drives, no D drive. Using the console I can see that Z contains the files on my host, but I am unable to enable the Z drive in Backblaze as it throws a unable to create .bzvol folder error. Is anyone else running into this and if so how do we fix it?

**Comment by jbschooley** [comment]
Just went through this myself and it's buried deep in the instructions. You have to run `docker exec --user app backblaze_personal_backup ln -s /drive_d/ /config/wine/dosdevices/d:` after setting up wine and signing in, then restart the container and the D drive will show up.

Note, DO NOT try to map your share directly to `/config/wine/dosdevices/d:` as it'll try to reset permissions for everything in there.

**Comment by cpsmith516** [comment]
jbschooley - thank you, this resolved it for me as well

**Comment by ScribbleGhost** [comment]
Sorry if I am reopening this unnecessary, but I am having the same problem (not being able to create .bzvol) but I don't understand how I should configure this on Unraid. Some help would be much appreciated.
