### ISSUE TITLE
Computer is offline - requires manual intervention

### ISSUE THREAD

**Issue by johnnyfleet** [JonathanTreffler/backblaze-personal-wine-container#81]
I'm not sure why but everytime I run this is works fine for a good while, backing up all the files. Then after a while I get the following error `Computer is offline. Check your internet connection. Will retry at 4:31`. 

I can't seem to understand why it is stopping as the internet is stable. I can force restart it or wait and it will resume later. The problem is the auto-resume means the backups take forever. 

![image](https://github.com/JonathanTreffler/backblaze-personal-wine-container/assets/14134347/69eb0fca-6c14-4278-afb7-4da3de4591dd)

Any suggestions why that may be? 

FWIW I'm running the latest image on Unraid 6.12.5

**Comment by johnnyfleet** [comment]
For some added context - it will run for about 10 minutes then stop ('offline') where it waits for about 10 minutes then will resume. This will go for another 10-20 minutes before stopping again.

**Comment by traktuner** [comment]
Hey @johnnyfleet !
Could you please add to the latest version? At container start, a Backblaze update should pop up (may take some time for the updater to show up, you may see a black screen for some time) and let us know if the issue persists? Thank you!

**Comment by johnnyfleet** [comment]
Thanks @traktuner - I've fired it up today. Seems to have auto updated a week ago. I normally have it fire up on a schedule 1am-6am to manually started in the day. However I seem to be sat on the blank screen for 30 mins with no progress. Also backblaze console seems to show that it has been idle/not backing up for 10 days.

I'll start fresh with a new container instance and empty config/appdata folder to see if I get it to kick back into life. I'll keep you posted.

**Comment by johnnyfleet** [comment]
Adding note as potentially related to #88

**Comment by johnnyfleet** [comment]
Hmmm - more interesting. So I removed the current container and deleted the config folder (well renamed elsewhere). When I downloaded the latest version and set up in unraid using the defined template I get a permission error. It seems no different if I chmod 777 the config folder and restart the container. Log extract below:


```
[app         ] + disclaimer_updatemode                                                                                                                                                                        
│   [app         ] + [ false = true ]                                                                                                                                                                             
│   [app         ] + [ false = true ]                                                                                                                                                                            
│   [app         ] + echo FORCE_LATEST_UPDATE is disabled. Using known-good version of Backblaze.                                                                                                                 
│   [app         ] FORCE_LATEST_UPDATE is disabled. Using known-good version of Backblaze.                                                                                                                        
│   [app         ] + [ -f /config/wine/drive_c/Program Files (x86)/Backblaze/bzbui.exe ]                                                                                                                          
│   [app         ] + mkdir -p /config/wine/                                                                                                                                                                       
│   [app         ] + [ false = true ]                                                                                                                                                                             
│   [app         ] + log_message INSTALLER: FORCE_LATEST_UPDATE=false, Installing pinned Backblaze version                                                                                                        
│   [app         ] /startapp.sh: 159: log_message: not found                                                                                                                                                      
│   [app         ] + sleep infinity                                                                                                                                                                               
│   [app         ] + curl -A backblaze-personal-wine/v1.6 (JonathanTreffler, +https://github.com/JonathanTreffler/backblaze-personal-wine-container), CFNetwork -L https://web.archive.org/web/20231218152237/h   │
│   ttps://secure.backblaze.com/win32/install_backblaze.exe --output install_backblaze.exe                                                                                                                        
│   [app         ]   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                                                                                                                
│   [app         ]                                  Dload  Upload   Total   Spent    Left  Speed                                                                                                                  
│   [supervisor  ] all services started.                                                                                                                                                                          
│   [app         ]   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0                                                                                                                 
│   [app         ]   0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0                                                                                                                 
│   [app         ]   0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0Warning: Failed to create the file install_backblaze.exe: Permission denied                                      │
│   [app         ]   0 27.7M    0 13626    0     0   4706      0  1:43:07  0:00:02  1:43:05  4705                                                                                                                 
│   [app         ] curl: (23) Failed writing body (0 != 13626)     
```

**Comment by johnnyfleet** [comment]
And oddly I experimented by taking unraid out of the equation. I spun up locally on my laptop (Manjaro) using the standard guidance 

``` bash
docker run \
    -p 8080:5800 \
    --init \
    --name backblaze_personal_backup \
    -v "/home/user/Documents/:/drive_d/" \
    -v "/home/user/docker/backblaze-personal-wine/:/config/" \
    tessypowder/backblaze-personal-wine:latest
 ```
 When I try this method I get a timeout getting the exe from web.archive.org.  I've checked and disabled any network elements which could be interfering e.g. tailscale, ufw etc. 
 
 If I paste that URL directly into the browser on laptop it downloads fine. I'll have to do some more digging here. 
 
 Logs from the laptop
 
 ```
 [app         ] + cat /RELEASE_VERSION
[app         ] + release_version=v1.6
[app         ] + local_version_file=/config/wine//dosdevices/c:/ProgramData/Backblaze/bzdata/bzreports/bzserv_version.txt
[app         ] + install_exe_path=/config/wine//dosdevices/c:/
[app         ] + log_file=/config/wine//dosdevices/c:/backblaze-wine-startapp.log
[app         ] + custom_user_agent=backblaze-personal-wine/v1.6 (JonathanTreffler, +https://github.com/JonathanTreffler/backblaze-personal-wine-container), CFNetwork
[app         ] + pinned_bz_version_file=/PINNED_BZ_VERSION
[app         ] + sed -n 1p /PINNED_BZ_VERSION
[app         ] + pinned_bz_version=9.0.0.749
[app         ] + sed -n 2p /PINNED_BZ_VERSION
[app         ] + pinned_bz_version_url=https://web.archive.org/web/20231218152237/https://secure.backblaze.com/win32/install_backblaze.exe
[app         ] + export WINEARCH=win64
[app         ] + disclaimer_updatemode
[app         ] + [ false = true ]
[app         ] + [ false = true ]
[app         ] + echo FORCE_LATEST_UPDATE is disabled. Using known-good version of Backblaze.
[app         ] FORCE_LATEST_UPDATE is disabled. Using known-good version of Backblaze.
[app         ] + [ -f /config/wine/drive_c/Program Files (x86)/Backblaze/bzbui.exe ]
[app         ] + mkdir -p /config/wine/
[app         ] + [ false = true ]
[app         ] + log_message INSTALLER: FORCE_LATEST_UPDATE=false, Installing pinned Backblaze version
[app         ] /startapp.sh: 159: log_message: not found
[app         ] + sleep infinity
[app         ] + curl -A backblaze-personal-wine/v1.6 (JonathanTreffler, +https://github.com/JonathanTreffler/backblaze-personal-wine-container), CFNetwork -L https://web.archive.org/web/20231218152237/https://secure.backblaze.com/win32/install_backblaze.exe --output install_backblaze.exe
[app         ]   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[app         ]                                  Dload  Upload   Total   Spent    Left  Speed
[app         ]   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[supervisor  ] all services started.
[app         ]   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[app         ]   0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
[app         ]   0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
[app         ]   0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
[app         ]   0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
[app         ]   0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
[app         ]   0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--     0
[app         ]   0     0    0     0    0     0      0      0 --:--:--  0:00:07 --:--:--     0
[app         ]   0     0    0     0    0     0      0      0 --:--:--  0:00:08 --:--:--     0
[app         ]   0     0    0     0    0     0      0      0 --:--:--  0:00:09 --:--:--     0
[app         ]   0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0
[app         ]   0     0    0     0    0     0      0      0 --:--:--  0:00:11 --:--:--     0
[app         ]   0     0    0     0    0     0      0      0 --:--:--  0:00:12 --:--:--     0
[app         ]   0     0    0     0    0     0      0      0 --:--:--  0:00:13 --:--:--     0
[app         ]   0     0    0     0    0     0      0      0 --:--:--  0:00:14 --:--:--     0
[app         ]   0     0    0     0    0     0      0      0 --:--:--  0:00:15 --:--:--     0
[app         ]   0     0    0     0    0     0      0      0 --:--:--  0:00:16 --:--:--     0
[app         ]   0     0    0     0    0     0      0      0 --:--:--  0:00:17 --:--:--     0
[app         ]   0     0    0     0    0     0      0      0 --:--:--  0:00:18 --:--:--     0
[app         ]   0     0    0     0    0     0      0      0 --:--:--  0:00:19 --:--:--     0
[app         ]   0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0
[app         ]   0     0    0     0    0     0      0      0 --:--:--  0:00:21 --:--:--     0
[app         ]   0     0    0     0    0     0      0      0 --:--:--  0:00:22 --:--:--     0
[app         ]   0     0    0     0    0     0      0      0 --:--:--  0:00:23 --:--:--     0curl: (6) Could not resolve host: web.archive.org
```

**Comment by johnnyfleet** [comment]
And for reference this is the webui I get. No surprises if the exe can't download: 

![image](https://github.com/JonathanTreffler/backblaze-personal-wine-container/assets/14134347/0673b77b-9161-4402-8be0-9fe18b71eeea)

**Comment by traktuner** [comment]
Thanks for the logs!
The download link works perfectly, and "could not resolve host" looks like an issue on your docker host (DNS or internet connection) which is for sure an indicator for the "computer is offline" issue you described in your initial pot.
Backblaze tries to ping a few different URls frequently to check if it can connect to the internet. If that's not possible, you'll get the "computer is offline" message. More background on this here:
https://www.reddit.com/r/backblaze/comments/fn8bbb/comment/fl8e1mq/?utm_source=share&utm_medium=web2x&context=3

You can try 2 things:
1) ssh into the docker container and try to ping archive.org or web.archive.org
2) Instead of the latest tag, please try ubuntu22 instead

If you still get the error, it's definetely an issue with your unraid docker setup. If you have a local DNS server, make exceptions or disable it, try different DNS providers on your docker host, ...
Unfortunately I'm not much help to you because I have no unraid system.

**Comment by johnnyfleet** [comment]
Yup you're right - the networking was a red herring on laptop. But I've recreated the same error as unraid now (good...consistent).

My docker networking on local laptop was screwed as I couldn't even ping on a base ubuntu container. I reinstalled OS to reset networking and confirmed thats all working now. Now, however, I get the permission denied error that I got on unraid (see below). this is with `latest` and `ubuntu22` tags. 


```bash
[app         ] + curl -A backblaze-personal-wine/v1.6.1 (JonathanTreffler, +https://github.com/JonathanTreffler/backblaze-personal-wine-container), CFNetwork -L https://web.archive.org/web/20240126203244/https://secure.backblaze.com/win32/install_backblaze.exe --output install_backblaze.exe
[app         ]   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[app         ]                                  Dload  Upload   Total   Spent    Left  Speed
[supervisor  ] all services started.
[app         ]   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[app         ]   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[app         ]   0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0Warning: Failed to create the file install_backblaze.exe: Permission denied
[app         ]   0 28.7M    0 13749    0     0   6454      0  1:17:47  0:00:02  1:17:45  6454
[app         ] curl: (23) Failure writing output to destination

```

**Comment by traktuner** [comment]
Great, we're making progress :)
The permission issue is because the docker container runs with different permissions, that means it can't write to a folder (the installer, config etc) to the local folder which then has different permissions.
You can add the environment variables USER_ID and GROUP_ID to your docker run command and those should match the user on your local system. you can chek them with id <username> on your system.
Then the container can write the installer, configs, etc to your disk.

**Comment by traktuner** [comment]
Thanks for testing!
Ultimately it's still a permission issue. The container wants to write to 
`/home/<user>/docker/backblaze_personal_backup` with the user 1000:1000 and can't write there.
You can try to set UID and GID to 0 (root). If that works, please try changing the permissions on your local folder.

**Comment by xela1** [comment]
I've submitted a pull request https://github.com/JonathanTreffler/backblaze-personal-wine-container/pull/110 that writes the download to /tmp rather than / when it's a new install (as well as fixing the log_message errors. 

If someone can review and approve the pull request, I believe these will solve the access denied issues without having to change USER_ID and GROUP_ID

**Comment by Brooklyn-Mark** [comment]
+1 to the black screen issue and unRAID not backing up since 12 days ago. Just noticed this happening. I haven't reinstalled the container and just tried putting in the UID and GID but that wasn't enough to get it going. Gonna try to re-install and see if that makes it work on my system.

**Comment by Brooklyn-Mark** [comment]
1 more thing to add @traktuner @JonathanTreffler where @xela1 suggestion might not be needed. In unRAID, it seems they don't have a typical user system like most distros. If the container supports it, they always recommend adding PGID (99) and PUID (100) [.](https://forums.unraid.net/topic/118751-puid-pgid-and-umask/)  and this gets rid of permissions error, but these must be able to be set in the container. 

Is it possible to add this ability, so that we can add these values in our templates and it should hopefully fix this issue?

**Comment by JonathanTreffler** [comment]
> 1 more thing to add @traktuner @JonathanTreffler where @xela1 suggestion might not be needed. In unRAID, it seems they don't have a typical user system like most distros. If the container supports it, they always recommend adding PGID (99) and PUID (100) [.](https://forums.unraid.net/topic/118751-puid-pgid-and-umask/) and this gets rid of permissions error, but these must be able to be set in the container.
> 
> Is it possible to add this ability, so that we can add these values in our templates and it should hopefully fix this issue?

Out container fully supports that and it is required on many distros. Please read the readme.

**Comment by xela1** [comment]
I'm fairly sure my pull request fixes a bug in the startapp.sh script when it's installing the client for the first time that was introduced in the new version with added auto update functionality, previously it would attempt to download to /config/wine (after creating if it didn't exist), the new version attempting to download to the working directory which is /. 

My pull request has it download to /tmp if it's a new install, although this could be changed to /config/wine if that makes more sense

**Comment by traktuner** [comment]
Hey @Brooklyn-Mark @johnnyfleet 
Any update from your side regarding this issue?
We have released version 1.7 yesterday with a few fixes and features.

**Comment by Brooklyn-Mark** [comment]
> Hey @Brooklyn-Mark @johnnyfleet Any update from your side regarding this issue? We have released version 1.7 yesterday with a few fixes and features.

I should get a chance to try dropping the ubuntu22 tag  and going with the latest tomorrow as well.  Work is busy today. Thanks @traktuner

**Comment by johnnyfleet** [comment]
Hmm ok - I tried pulling the latest image of `ubuntu22` tag. This time the web vnc viewer won't come up. 

![image](https://github.com/JonathanTreffler/backblaze-personal-wine-container/assets/14134347/e343c059-654b-47a8-9640-6d928dc78f6d)

Last part of logs: 

``` shell
[app         ] ------------------------------------------------------
[app         ] warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
[app         ] ------------------------------------------------------
[app         ] Using winetricks 20210206 - sha256sum: 0f21da98811e0bfda16a7d6d6b8e860a9cedbd4e836c7dd9b02f068d3092ee2e with wine-9.0 and WINEARCH=win64
[app         ] Executing wine regedit C:\windows\Temp/vd.reg
[app         ] Executing wine64 regedit C:\windows\Temp/vd.reg
[app         ] + '[' false = true ']'
[app         ] + '[' false = true ']'
[app         ] + echo 'FORCE_LATEST_UPDATE is disabled. Using known-good version of Backblaze.'
[app         ] FORCE_LATEST_UPDATE is disabled. Using known-good version of Backblaze.
[app         ] + '[' -f '/config/wine/drive_c/Program Files (x86)/Backblaze/bzbui.exe' ']'
[app         ] + fetch_and_install
[app         ] + cd /config/wine/dosdevices/c:/
[app         ] + '[' false = true ']'
[app         ] + log_message 'INSTALLER: FORCE_LATEST_UPDATE=false - downloading pinned version 9.0.1.763 from archive.org'
[app         ] ++ date
[app         ] + echo 'Thu Feb 15 05:02:10 AM UTC 2024: INSTALLER: FORCE_LATEST_UPDATE=false - downloading pinned version 9.0.1.763 from archive.org'
[app         ] + curl -A 'backblaze-personal-wine/v1.7 (JonathanTreffler, +https://github.com/JonathanTreffler/backblaze-personal-wine-container), CFNetwork' -L https://web.archive.org/web/20240126203244/https://secure.backblaze.com/win32/install_backblaze.exe --output install_backblaze.exe
[app         ]   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[app         ]                                  Dload  Upload   Total   Spent    Left  Speed
[app         ]   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[app         ]   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[app         ]   0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
[app         ]   0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
[app         ]   0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
[app         ]   0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
[app         ]   0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
[app         ]   0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--     0
[app         ]   0     0    0     0    0     0      0      0 --:--:--  0:00:07 --:--:--     0
[app         ]   0     0    0     0    0     0      0      0 --:--:--  0:00:08 --:--:--     0
[app         ]   0     0    0     0    0     0      0      0 --:--:--  0:00:09 --:--:--     0
[app         ]   0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0
[app         ]   0     0    0     0    0     0      0      0 --:--:--  0:00:11 --:--:--     0curl: (6) Could not resolve host: web.archive.org
[app         ] + handle_error 'INSTALLER: error downloading from https://web.archive.org/web/20240126203244/https://secure.backblaze.com/win32/install_backblaze.exe'
[app         ] + echo 'Error: INSTALLER: error downloading from https://web.archive.org/web/20240126203244/https://secure.backblaze.com/win32/install_backblaze.exe'
[app         ] + start_app
[app         ] ++ cat /config/wine/dosdevices/c:/ProgramData/Backblaze/bzdata/bzreports/bzserv_version.txt
[app         ] cat: '/config/wine/dosdevices/c:/ProgramData/Backblaze/bzdata/bzreports/bzserv_version.txt': No such file or directory
[app         ] + log_message 'STARTAPP: Starting Backblaze version '
[app         ] ++ date
[app         ] + echo 'Thu Feb 15 05:02:22 AM UTC 2024: STARTAPP: Starting Backblaze version '
[app         ] + sleep infinity
[app         ] + wine64 '/config/wine/drive_c/Program Files (x86)/Backblaze/bzbui.exe' -noquiet
[app         ] wine: failed to open "/config/wine/drive_c/Program Files (x86)/Backblaze/bzbui.exe": c0000135
```

And the docker command I used:

``` shell
docker run \
    -p 8080:5800 \
    --init \
    --name backblaze_personal_backup \
    -v "/home/<user>/Documents/:/drive_d/" \
    -v "/home/<user>/docker/backblaze_personal_backup:/config/" \
    tessypowder/backblaze-personal-wine:ubuntu22
```
  
Before I run I make sure to delete the config folder on host for clean set up. 

Oddly I think it ran fine on the version from last weekend when I last tried briefly. Maybe an issue introduced in latest version? 

I seem to be getting similar results on Unraid too.

I'll try and do a little more troubleshooting

**Comment by traktuner** [comment]
> ```shell
> curl: (6) Could not resolve host: web.archive.org
> ```

You have a DNS or network issue with your Docker host. The latest Backblaze version which we tested and is compatible will always be downloaded from archive.org instead of backblaze.com itself, since officially only the latest version is availabe for download there, and we may be several releases behind.
This has nothing to do with our container image of Backblaze itself.

**Comment by johnnyfleet** [comment]
Yeah good spot. Sorry I was running on the commute so could be patchy 4G causing it. 

I'll test out some more. I'll check the logs of Unraid too as showing the same vnc issue. I think last time when had issues downloading it at least would show a blank screen in vnc like the first screenshot on this issue thread.

**Comment by johnnyfleet** [comment]
Yeah good spot. Sorry I was running on the commute so could be patchy 4G causing it. 

I'll test out some more. I'll check the logs of Unraid too as showing the same vnc issue. I think last time when had issues downloading it at least would show a blank screen in vnc like the first screenshot on this issue thread.

**Comment by johnnyfleet** [comment]
All seems to be looking a lot better now thanks. Must have been patchy 4G as worked fine at home on laptop. Also set up again on Unraid and looking good with the `ubuntu22` tag. I'll switch to the latest over the weekend and try that too. 

The original issue was intermittent disconnects. I've reconnected and inherited my license again in backblaze so I'll see how the syncing goes now and whether I see the issue again. 

If all fine I'll close the ticket over the weekend. 

Thanks all for the help.

**Comment by johnnyfleet** [comment]
Thanks all. It's been running for a while and all looking good.

I haven't had the offline issue return so I'll close this issue 

Appreciate the help looking into it.
