### ISSUE TITLE
Drive D is Now "Unplugged"?

### ISSUE THREAD

**Issue by newoski** [JonathanTreffler/backblaze-personal-wine-container#94]
As of roughly December 7th, my docker on Unraid is showing Drive D as (Unplugged) and it no longer sees the drive. As a result, upload is broken. There are also posts on the Unraid forum from another user having the same problem. I have tried deleting and reinstalling the docker, but the (Unplugged) status for Drive D is consistently there now.

**Comment by xela1** [comment]
Are you still having this problem, can you open a shell on unraid and run the following

`docker exec --user app -it _containername_ wine64 explore`

and send a screenshot of the My Computer window

![image](https://github.com/JonathanTreffler/backblaze-personal-wine-container/assets/357319/a6ae1f00-df46-47fe-b987-016e445779e0)

**Comment by newoski** [comment]
The settings I shared in this post fixed the issue. Had to grant additional permissions in Unraid docker setup 

https://forums.unraid.net/topic/87798-support-selfhostersnets-template-repository/?do=findComment&comment=1354928

**Comment by Schaka** [comment]
In my case, none of that helped. Making sure the additional arguments (in Unraid) included `--privileged` and manually linking each drive seems to have done the trick. They weren't being picked up automatically.

So I would map them (via Unraid) like
- Container Path: /drive/e
- Host path: /mnt/user/backup (this is an Unraid share)

Then I'd connect via SSH and do 
`docker exec --user app backblaze_personal_backup ln -s /drive_d /config/wine/dosdevices/d:``

After restarting the container, drives were recognized.

**Comment by newoski** [comment]
My entire docker broke after the latest update. I’m going to rebuild from
scratch w your tips and will report back asap
